### ISSUE TITLE
[BSP] buildTarget/javacOptions not implemented.

### ISSUE THREAD

**Issue by sequencer** [lihaoyi/mill#1022]
Intellij 2020.3 seem picked this [commit](https://github.com/JetBrains/intellij-scala/commit/c1944e558dc3bd22f2c8a68f221d573e077b1088), mill import failed since not implementing `buildTarget/javacOptions`

**Comment by joan38** [comment]
Same as https://github.com/lihaoyi/mill/issues/1024 and fixed by https://github.com/lihaoyi/mill/pull/1025
Thanks again @sequencer
