### ISSUE TITLE
BSP failing on Intellij with buildTarget/javacOptions not implemented

### ISSUE THREAD

**Issue by joan38** [lihaoyi/mill#1024]
Sounds like we need to implement buildTarget/javacOptions

**Comment by sequencer** [comment]
just implemented in #1023, need some review?

**Comment by joan38** [comment]
Thanks @sequencer and sorry about the clash of PRs.

**Comment by Iltotore** [comment]
Hello, after compiling Mill from this PR, [I still have this problem](https://youtrack.jetbrains.com/issue/SCL-18519). Are you sure it is solved now ?

**Comment by sequencer** [comment]
@Iltotore use #1025, rather than #1024.

**Comment by muya** [comment]
FWIW, this error on my IntelliJ (IntelliJ IDEA 2020.3.2 (Ultimate Edition) Build #IU-203.7148.57) went away after invalidating cache & restarting
