### ISSUE TITLE
[CI bug] Release Source code is not up-to-date with codes

### ISSUE THREAD

**Issue by sequencer** [lihaoyi/mill#1030]
If consider 0.9.3-x as backport to 0.9.3, tag should be updated to, if not, distribution packagers cannot find correct source and rebuild.
Same issue also exist in ammonite.

**Comment by lefou** [comment]
Sorry, but I don't quite understand the issue. Can you elaborate?

Updating / changing tags isn't a good option after there are already consumers. But we can release a `0.9.4` as soon as we are confident we fixed the BSP issue of `0.9.3`.

**Comment by sequencer** [comment]
In the [release](https://github.com/lihaoyi/mill/releases) page, there are 13 commits upon 0.9.3. I don’t know should I consider newest version is stable or the first version of 0.9.3 is stable?
If first version of 0.9.3 is stable, means bug fixes on master branch won’t backport to real 0.9.3. And can only wait until 0.9.4 comes to fix the bug.
If newest version of 0.9.3 is stable, means distribution packager should download the source of newest version. So tag should be updated.

**Comment by lefou** [comment]
There is exactly one `0.9.3` release, it's the one that has the git tag and is published to Maven and GitHub with the exact version `0.9.3`. All other published versions under `0.9.3` release page are post `0.9.3` snapshot releases.
See http://www.lihaoyi.com/mill/#development-releases and http://www.lihaoyi.com/mill/#overriding-mill-versions
