### ISSUE TITLE
Use coursier instead of ivy

### ISSUE THREAD

**Issue by erikvanoosten** [lihaoyi/mill#105]
Rationale: life is too short to wait for the internet to download.

**Comment by rtimush** [comment]
I think coursier is already used everywhere in mill

**Comment by rockjam** [comment]
@erikvanoosten yep, coursier is already used to resolve deps in mill: https://github.com/lihaoyi/mill/blob/master/scalalib/src/main/scala/mill/scalalib/Lib.scala#L171 here it is

**Comment by erikvanoosten** [comment]
Awesome! I'll read the documentation again to find out why I though Ivy was used.

**Comment by erikvanoosten** [comment]
I see now. The repl example in the README.md has this fragment:

```@ core.ivyDeps()
Running core.ivyDeps
res5: Seq[scalalib.Dep] = List(
  Scala(
    Dependency(
      Module("com.lihaoyi", "sourcecode", Map()),
      "0.1.4",
...
```
