### ISSUE TITLE
GenIdea doesn't support resources correctly. Resources will not appear in the compiler output folder

### ISSUE THREAD

**Issue by molikto** [lihaoyi/mill#112]
This causes, for example, the mill `build.sc` file itself fails to compile when run/debug mill within IntelliJ IDEA. Because the `scalac-plugin.xml` resource file is not in `/out/moduledefs/compile/dest/classes` folder (which is assigned as compiler output folder by current GenIdea implementation

**Comment by lihaoyi** [comment]
Shouldn't Intellij be able to pick up `scalac-plugin.xml` from the `resources` directly? We could copy the files, but any downstream should be able to handle the fact that the classpath contains multiple paths, one of which is the `resources/` folder
