### ISSUE TITLE
Support for package lock file

### ISSUE THREAD

**Issue by sideeffffect** [lihaoyi/mill#120]
The file should record the concrete dependency resolution (including version) of all direct and transitive dependencies of the project. It should be maintained by `mill`.

Inspiration:

https://github.com/tkawachi/sbt-lock

https://github.com/sbt/sbt/wiki/User-Stories:--Offline-mode-and-Dependency-Locking#the-dependency-lockfile

https://fsprojects.github.io/Paket/lock-file.html

https://doc.rust-lang.org/cargo/guide/cargo-toml-vs-cargo-lock.html

https://richonrails.com/articles/how-does-the-gemfile-lock-file-work

**Comment by lihaoyi** [comment]
Closing this for later; when it comes up on our roadmap we'll re-open it

**Comment by sideeffffect** [comment]
interestingly, even Microsoft's NuGet is getting support for `lock` file ([1](https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files#locking-dependencies), [2](https://twitter.com/PaketManager/status/1059715954085711872))
@lihaoyi would you consider including this feature in `mill`'s roadmap now? what would be the blockers?
