### ISSUE TITLE
Automate CI publishing to Github-Releases/Maven-Central

### ISSUE THREAD

**Issue by lihaoyi** [lihaoyi/mill#122]
We should publish all necessary to a snapshot version e.g. suffixed by `-COMMITabcdef` every commit to master, and publish a stable version e.g. `0.0.1` every time a tag is pushed, based on the name of the tag.

This will make it much easier for us to work on Mill while simultaneously making use of it in other projects

**Comment by SethTisue** [comment]
(https://github.com/scalacenter/sbt-release-early?)

**Comment by lihaoyi** [comment]
Probably a python/Ammonite script, since we won't have an SBT build in future

**Comment by nafg** [comment]
You can make a Mill version of sbt-release-early first. ;)
Anyway it shouldn't be a big deal in any case. Deploying to bintray can
even be done with curl.

**Comment by rockjam** [comment]
Are we okay with maven central synchronization lag for commit artifacts?

**Comment by lihaoyi** [comment]
Sure, the whole world pays the synchronization lag, I don't think we are in any way special

**Comment by lihaoyi** [comment]
This has happened https://github.com/lihaoyi/mill/releases
