### ISSUE TITLE
GenIdeaModule task does not generate correct Idea files

### ISSUE THREAD

**Issue by miroslavraska** [lihaoyi/mill#129]
Reproducible e.g. in mill repository
- run `mill mill.scalalib.GenIdeaModule/idea`
- this generates `.idea` and `.idea_modules` directories
- open project in idea
- only `root` module is present in Project Structure
- Project JDK and Scala SDK are not set properly

**Comment by lihaoyi** [comment]
This should be fixed in master. I don't remember when I fixed it, but I did
