### ISSUE TITLE
Scala-Native support

### ISSUE THREAD

**Issue by lihaoyi** [lihaoyi/mill#142]
Scala Native is a thing now, and I'd like to use Mill to develop Scala Native applications

Scala.js didn't turn out to be that hard to support, so hopefully Scala Native won't be too much work either

**Comment by MasseGuillaume** [comment]
Keep an eye open on https://github.com/scala-native/scala-native/pull/1143

**Comment by ajrnz** [comment]
See PR#206

**Comment by lihaoyi** [comment]
Landed in 0.2.5
