### ISSUE TITLE
Compile against stripped interfaces of upstream modules

### ISSUE THREAD

**Issue by lihaoyi** [lihaoyi/mill#143]
If we strip out the implementation of intermediate compile output like Bazel does, it could save us a bunch of spurious re-compiles when you change a method body but Zinc isn't clever enough to figure out that downstreams don't need to recompile.

We only need to use the "real" compiled output of upstream modules 1) if you are using macros from that module or 2) you actually want to run the code

Bazel has some special hand-rolled C++ stripped called `ijar`, but we could probably get away with just using ASM or something

**Comment by rockjam** [comment]
Is it already implemented in zinc?
