### ISSUE TITLE
foo.console java.lang.NullPointerException

### ISSUE THREAD

**Issue by qqke** [lihaoyi/mill#146]
mill foo.console
[28/28] foo.console 
1 targets failed
foo.console java.lang.NullPointerException
    ammonite.ops.Shellout$.executeInteractive(Shellout.scala:23)
    ammonite.ops.Shellout$.$anonfun$$percent$1(Shellout.scala:14)
    ammonite.ops.Shellout$.$anonfun$$percent$1$adapted(Shellout.scala:14)
    ammonite.ops.Command.applyDynamic(Shellout.scala:118)
    mill.modules.Jvm$.interactiveSubprocess(Jvm.scala:37)
    mill.scalalib.ScalaModule.$anonfun$console$2(ScalaModule.scala:246)
    scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)

**Comment by lihaoyi** [comment]
Should be fixed in master, can you try https://github.com/lihaoyi/mill/releases/download/unstable/0.1.1-5-9c464c
