### ISSUE TITLE
Generated idea project reports error `Error:scalac: No 'scala-library*.jar' in Scala compiler classpath in Scala SDK org_scala-lang_scala-library_2.12.4_scala-library-2.12.4-sources.jar` when compiling

### ISSUE THREAD

**Issue by freewind** [lihaoyi/mill#147]
In a mill project:

```
mill mill.scalalib.GenIdeaModule/idea
```

Then open idea and set scala project, and build.

It reports:

```
Error:scalac: No 'scala-library*.jar' in Scala compiler classpath in Scala SDK org_scala-lang_scala-library_2.12.4_scala-library-2.12.4-sources.jar
```
![image](https://user-images.githubusercontent.com/333781/36488712-1e37352e-175f-11e8-8601-85d7f1a63bf3.png)

Check the scala related library, I see

![image](https://user-images.githubusercontent.com/333781/36488954-bad8b92a-175f-11e8-8ed7-78f53ae8fc87.png)

Which has empty compiler classpath.

To fix it, I need to remove the two libraries:

- org_scala-lang_scala-library_2.12.4_scala-library-2.12.4.jar
- org_scala-lang_scala-library_2.12.4_scala-library-2.12.4-sources.jar

And add the scala sdk provided by IDEA, which is like:

![image](https://user-images.githubusercontent.com/333781/36489057-0183d5d0-1760-11e8-863c-8ea85660d00b.png)

**Comment by ajrnz** [comment]
I'm happy to have a look at this. I'm looking at making the dependencies get correctly allocated to sub modules and a few other improvements to to GenIdea

**Comment by lihaoyi** [comment]
@ajrnz go for it
