### ISSUE TITLE
Wondering why the generate jdk name is "1.8 (1)" rather than "1.8"?

### ISSUE THREAD

**Issue by freewind** [lihaoyi/mill#152]
The IDEA project generated by `mill mill.scalalib.GenIdeaModule/idea` has a JDK named `1.8 (1)`, and I also see the code:

```
val jdkInfo = extractCurrentJdk(pwd / ".idea" / "misc.xml").getOrElse(("JDK_1_8", "1.8 (1)"))
```

I'm wondering why choose `1.8 (1)` rather than `1.8`? I have this question because in my IDEA (in mac), when I create a JDK based on my jdk1.8 installation, the generated name is `1.8`

**Comment by lihaoyi** [comment]
You should ask questions on gitter instead of the issue tracker

**Comment by miroslavraska** [comment]
@lihaoyi I'm interested in this question also..

And IMHO it's not the best approach to discuss topics like that on gitter, because it's really hard to find something in the discussion thread. If you address this question here, it might help other mill users in the future.

**Comment by freewind** [comment]
Actually, I think this is an issue more than a question, so I asked here
