### ISSUE TITLE
Broken on Java 9

### ISSUE THREAD

**Issue by ashawley** [lihaoyi/mill#156]
I couldn't use mill because ammonite doesn't work on Java 9.  I ran in to lihaoyi/Ammonite#675

Anyway... you should mention in the docs that it only supports Java 8.

**Comment by francisdb** [comment]
That ticket mentions OpenJDK9 but indeed mill also doesn't work with OracleJDK9

```
mill -i
Loading...
Compiling (synthetic)/ammonite/predef/interpBridge.sc
java.lang.ExceptionInInitializerError
  ammonite.interp.CompilerLifecycleManager.init(CompilerLifecycleManager.scala:75)
  ammonite.interp.CompilerLifecycleManager.preprocess(CompilerLifecycleManager.scala:49)
  ...
java.lang.NullPointerException
  ammonite.runtime.Classpath$.<init>(Classpath.scala:30)
  ammonite.runtime.Classpath$.<clinit>(Classpath.scala)
  ammonite.interp.CompilerLifecycleManager.init(CompilerLifecycleManager.scala:75)
  ammonite.interp.CompilerLifecycleManager.preprocess(CompilerLifecycleManager.scala:49)
  ammonite.interp.Interpreter.compileRunBlock$1(Interpreter.scala:486)
  ammonite.interp.Interpreter.$anonfun$processAllScriptBlocks$9(Interpreter.scala:525)
  ...
```

And a non-interactive run just hangs forever
```
mill _.compile
```

**Comment by francisdb** [comment]
I guess this can be closed?

**Comment by lihaoyi** [comment]
@francisdb no idea, I'll close it if @robby-phd says it can be closed :)

**Comment by ashawley** [comment]
I don't get the NPE in 0.1.5 when interactive, but now I get the hanging behavior with non-interactive.

**Comment by robby-phd** [comment]
@ashawley Can you try https://github.com/lihaoyi/mill/releases/download/0.1.5/0.1.5-3-a9d4ee?

**Comment by ashawley** [comment]
That version worked for me.

> Btw, it takes some time to boot up on Java 9 for the first time

I wouldn't know if it's fast or slow, this is the first time I've used mill.

> perhaps it's good to print info message that it's starting on Java 9

I wouldn't know if it's necessary or not.
