### ISSUE TITLE
Set up CI infrastructure

### ISSUE THREAD

**Issue by rockjam** [lihaoyi/mill#16]
Sooner or later, we'll need a CI for mill. We could start it sooner, to have more confidence when merging PR's

**Comment by lihaoyi** [comment]
Now that the repo is public, we should make this happen. There is already a `test.sh` script we can use that runs through the common SBT/bootstrapped workflows and makes sure everything works

**Comment by piotrkwiecinski** [comment]
I should be able to help with setting up travis.

**Comment by rockjam** [comment]
@piotrkwiecinski There is one issue that needs to be fixed to CI work correctly. `mill` doesn't return non-zero return code when the command fails. @lihaoyi Is it correct?

**Comment by rockjam** [comment]
It should be fixed in this PR https://github.com/lihaoyi/mill/pull/97

**Comment by rockjam** [comment]
Closed by #100 and #107
