### ISSUE TITLE
Exception on publishing library

### ISSUE THREAD

**Issue by AlexITC** [lihaoyi/mill#162]
I'm trying to publish a library to sonatype using the command `mill playsonify.publish ...` as it is specified in the docs, sadly, I'm getting this exception:

```
[39/42] playsonify.docJar 
Error: Could not find or load main class scala.tools.nsc.ScalaDoc
1 targets failed
playsonify.docJar ammonite.ops.InteractiveShelloutException
    mill.modules.Jvm$.subprocess(Jvm.scala:145)
    mill.scalalib.ScalaModule.$anonfun$docJar$2(ScalaModule.scala:175)
    mill.define.ApplyerGenerated.$anonfun$zipMap$1(ApplicativeGenerated.scala:5)
    mill.define.Task$MappedDest.evaluate(Task.scala:358)
    mill.eval.Evaluator.$anonfun$evaluateGroup$14(Evaluator.scala:297)
    scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
    scala.Console$.withErr(Console.scala:192)
    mill.eval.Evaluator.$anonfun$evaluateGroup$13(Evaluator.scala:297)
    scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
    scala.Console$.withOut(Console.scala:163)
```

I'm thinking that this could be a problem related to my environment, in case that it helps, I'm facing the problem with this project: https://github.com/AlexITC/playsonify

I forget to mention that running `mill playsonify.docJar` gives me the same error.

**Comment by lihaoyi** [comment]
This should be fixed in the latest unstable version, can you try it (`sudo curl -L -o /usr/local/bin/mill https://github.com/lihaoyi/mill/releases/download/unstable/0.1.1-36-7b7044 && sudo chmod +x /usr/local/bin/mill`)

**Comment by AlexITC** [comment]
It worked, thanks!

As a suggestion, I see that you are using your blog to post `mill` documentation, in this particular case, the version upgrade has a breaking change where I needed to update my build definition, if you version the documentation, it would be simpler for users to avoid these kind of issues when they want to use a specific version, thanks!
