### ISSUE TITLE
Some ScalaJSModule objects do not produce .sjsir files

### ISSUE THREAD

**Issue by robby-phd** [lihaoyi/mill#164]
The expectation is that mill build object that is an instance of ScalaJSModule should be compiled with Scala.js, thus producing .sjsir files, and associated tests run properly.

However, the followings show that sometimes it's not always the case.

### With ScalaTest

```bash
git clone -b master https://github.com/sireum/runtime.git runtime-scalatest && cd runtime-scalatest && git checkout c091fbd && mill library.js.tests.test
```
This outputs `library.js.tests.test org.scalajs.testcommon.RPCCore$RPCException`. 

No .sjsir files are produced under `out`.

### With utest

```bash
git clone -b utest https://github.com/sireum/runtime.git runtime-utest && cd runtime-utest && git checkout 51faded && mill library.js.tests.test
```

This outputs a bunch of `TypeError: Cannot read property '<test-class-name>' of undefined`.

Similarly, no .sjsir files are produced under `out`.

**Comment by rockjam** [comment]
@robby-phd will take a look at this, thanks for report

**Comment by robby-phd** [comment]
@rockjam Thank you! FYI, if you manage to make mill to produce .sjsir files but tests are still not running properly, it *might* be related to scala-js/scala-js#3174.

**Comment by lihaoyi** [comment]
@robby-phd could you try swapping the order of `ScalaJSModule` and `SireumModule` here? https://github.com/sireum/v3-runtime/blob/utest/sireum.sc#L116

**Comment by robby-phd** [comment]
@lihaoyi Still doesn't produce .sjsir files (even if that works, I think it'd better for users in general if mill is insensitive to trait inheritance ordering).

**Comment by rockjam** [comment]
> but tests are still not running properly

@robby-phd what's the issue with tests?

**Comment by robby-phd** [comment]
@rockjam There seems to be a bug with Scala.js that causes RPCCore$Exception even though .sjsir files are generated; this seems due to class export disappearing (see [Scala.js issue#3174](https://github.com/scala-js/scala-js/issues/3174) for more information).

If everything works, the expected test behavior in my case should be similar to what I get by running:

```bash
sbt "project libraryJS" test
``` 

That is, all tests should pass on both ScalaTest and utest versions.

**Comment by robby-phd** [comment]
After closer inspection, my custom module overrides ScalaJSModule's scalacPluginIvyDeps that's already populated with Scala.js plugin. The fix is to make sure to include the populated values when overriding mill module trait methods.

It would be nice if somehow mill "standard" modules such as ScalaJSModule do not fill default values that have to be included when users override methods such as scalacPluginIvyDeps. For now, I'm closing this ticket.

**Comment by lihaoyi** [comment]
Yeah it's a bit confusing when to user `super.foo()` and when not to
