### ISSUE TITLE
recursive value compile never ends

### ISSUE THREAD

**Issue by francisdb** [lihaoyi/mill#172]
mill 0.1.3
macOS 10.13.3 (17D47)

```
val scalaVersion = "2.12.4"
object utils extends SbtModule {
  def scalaVersion = scalaVersion
}
```

```
mill utils.compile
Compiling /Users/francisdb/workspace/WaylayEngine/build.sc
--hangs forever--
^C%
```

**Comment by AlexITC** [comment]
I feel that's something related to the scala compiler, you can reproduce the behavior in a REPL:
```
> def f: Unit = f
< <console>:7: warning: method f does nothing other than call itself recursively
       def f: Unit = f
> f
```

It will be the same, probably displaying the warning would be a good idea.

**Comment by lihaoyi** [comment]
That's not so much the compiler but the runtime; it seems unfortunately Scala automatically `@tailrec` optimizes such calls so you don't even get a proper stack-overflow. I suspect it would be pretty hard to detect such things at runtime

**Comment by francisdb** [comment]
I guess this can then just be closed?
