### ISSUE TITLE
How to configure credentials for private maven repos?

### ISSUE THREAD

**Issue by francisdb** [lihaoyi/mill#175]
Could not find any related documentation on fetching artifacts from a private maven repository.

sbt has `coursierUseSbtCredentials := true` which makes coursier look in the global sbt settings for credentials.

Is there anything similar available for mill where I could put the credentials in some file and Mill picking them up?

**Comment by rockjam** [comment]
Answered that in gitter. We could add current options in mill's documentation, I guess

**Comment by francisdb** [comment]
Would it not be better to have a standard way for storing these somewhere in the home dir of the user?

**Comment by rockjam** [comment]
Yes, it is. But someone should come up with PR for this

**Comment by francisdb** [comment]
From gitter:

> Li Haoyi @lihaoyi  17:05
> @francisdb Mill now supports a ~/.mill/ammonite/predef.sc file
> you can define your creds in there

**Comment by francisdb** [comment]
but maybe this should be added to the docs

**Comment by mallman** [comment]
@lefou Sorry, I'm confused. I want to specify credentials for a repo. I see this was marked as "fixed", but I don't see any documentation for it. (I'm looking at https://com-lihaoyi.github.io/mill/page/configuring-mill.html#adding-ivy-dependencies). Can you help with the fix/solution for this use case?

**Comment by lefou** [comment]
have you read the comments above? 

> From gitter:
> 
> > @francisdb mill uses coursier to resolve dependencies. You can add repositories to your build via
> 
> ```
>   def repositories: Seq[Repository] = super.repositories ++ Seq(
>     coursier.maven.MavenRepository("https://example.com", authentication = Some(coursier.core.Authentication("user", "password")))
>   )
> ```
> 
> > Li Haoyi @lihaoyi  17:05
> > @francisdb Mill now supports a ~/.mill/ammonite/predef.sc file
> > you can define your creds in there


It should look like this nowadays ...

```scala
override def repositoriesTask = T.task { super.repositoriesTask() ++ Seq(
  MavenRepository(
    // ...
    authentication = Some(Authentication("user", "pass"))
  )
)}
```

**Comment by mallman** [comment]
I understand, but I don't see how embedding credentials in a build file is a practical option. Is there a (standard) way to externalize credentials? I get the impression Mill doesn't support this kind of functionality because it's undocumented. Thank you.

**Comment by lefou** [comment]
Embedding credentials isn't a good idea. I currently don't use repos with credentials myself, so I haven't tested it. But I read the comment so, that you can define your repository in the `predef.sc`. Also. the `repositoriesTask` can depend on other tasks, including input tasks, so that you can read the credentials from other places, e.g. some environment variables.

**Comment by lefou** [comment]
See https://com-lihaoyi.github.io/mill/page/configuring-mill.html#global-configuration
