### ISSUE TITLE
predef.sc only loaded when running with -i

### ISSUE THREAD

**Issue by francisdb** [lihaoyi/mill#180]
I try to have a global `nexusUser` var I can use in multiple builds. See #175 

current setup for reproducing this issue

I created a broken  `~/.mill/ammonite/predef.sc` (contains a line with `--`)

```
(kill all java processes)
➜   git:(master) ✗ rm -rf out
➜   git:(master) ✗ mill -i
Loading...
Compiling (synthetic)/ammonite/predef/interpBridge.sc
Compiling /Users/francisdb/.mill/ammonite/predef.sc
predef.sc:3: not found: value --
val res_2 = --
            ^
Compilation Failed
(kill all java processes)
➜   git:(master) ✗ mill api.compile
Compiling (synthetic)/ammonite/predef/interpBridge.sc
Compiling /Users/francisdb/myproject/build.sc
build.sc:158: not found: value nexusUser
...
Compilation Failed
```

Instead of `build.sc` compilation failing it should fail on `predef.sc`

**Comment by lihaoyi** [comment]
@francisdb what if you do `mill -i api.compile`; does it load the `~/.mill/ammonite/predef.sc`, or does it not?

**Comment by francisdb** [comment]
nope, also skips predef

```
mill -i api.compile
Compiling (synthetic)/ammonite/predef/interpBridge.sc
Compiling (synthetic)/ammonite/predef/DefaultPredef.sc
Compiling /Users/francisdb/myproject/build.sc
```

**Comment by lihaoyi** [comment]
ok this is probably a bug/difference between the different code paths we use to load the REPL and to run scripts

**Comment by lihaoyi** [comment]
@francisdb can you try putting your predef in `~/.mill/ammonite/predefScript.sc`?

**Comment by francisdb** [comment]
That seems to work 👌
Is this documented somewhere?

```
mill _.compile
Compiling (synthetic)/ammonite/predef/interpBridge.sc
^[Compiling /Users/francisdb/.mill/ammonite/predefScript.sc
predefScript.sc:1: not found: value foo
val res = foo
          ^
Compilation Failed
```

```
mill -i
Loading...
Compiling (synthetic)/ammonite/predef/interpBridge.sc
Compiling /Users/francisdb/.mill/ammonite/predef.sc
predef.sc:3: not found: value --
val res_2 = --
            ^
Compilation Failed
```

**Comment by lihaoyi** [comment]
It's actually documented as part of Ammonite, whose script runner we build upon http://ammonite.io/#ScriptPredef. There's `predef.sc` for the REPL and `predefScript.sc` for scripts. Perhaps we can consolidate them later, but that would need more discussion.

Perhaps you can send a PR to add a one-line mention & link to the relevant part of our docs?

**Comment by francisdb** [comment]
The ammonite docs also mention `predefShared.sc` but that does not seem to be working
