### ISSUE TITLE
Mill seems to be incorrectly caching things across projects

### ISSUE THREAD

**Issue by lihaoyi** [lihaoyi/mill#184]
- https://github.com/lihaoyi/mill/issues/183
- https://github.com/lihaoyi/mill/issues/177

@freewind can you try and set up a minimal repro workflow that someone can use to reproduce the problem and fix it?

**Comment by freewind** [comment]
I can make it later

**Comment by lihaoyi** [comment]
Thanks @freewind!

**Comment by freewind** [comment]
@lihaoyi No worries:)

**Comment by Dennis4b** [comment]
This issue caused me the occasional headache, so for anyone dealing with the same, pending the proper fix (more specific keying on hash keys?) for which I'm not familiar enough with the internals, you can use the following patch to have the offending cache restricted to the `out/` folder local to the project.

```
diff --git a/main/src/mill/Main.scala b/main/src/mill/Main.scala
index 6c10f6f..8d71da3 100644
--- a/main/src/mill/Main.scala
+++ b/main/src/mill/Main.scala
@@ -59,7 +59,7 @@ object Main {
     val millArgSignature =
       Cli.genericSignature.filter(a => !removed(a.name)) :+ interactiveSignature
 
-    val millHome = home / ".mill" / "ammonite"
+    val millHome = pwd / "out" / ".mill" / "ammonite"
 
     Cli.groupArgs(
       args.toList,
```
Incidentally @freewind, both `mill-issue1-demo` and `mill-issue2-demo` output `Hello, Scala!` so to replicate the issue one should change the output to the intended `Hello, Mill Demo1!` and `2`, but it's clear what you meant, thanks!

**Comment by freewind** [comment]
@Dennis4b Thank you very much for pointing this out. I just checked the two repos, found I forgot to push the modified files, and just pushed them. It should be the correct output now.

**Comment by lihaoyi** [comment]
Found the bug. The problem is that Ammonite caches imported scripts based on their content hash and their package path:

```
(/Users/lihaoyi/.coursier/cache/v1/https/repo1.maven.org/maven2/org/scala-sbt/ipcsocket/ipcsocket/1.0.0/ipcsocket-1.0.0.jar,1515371702000)
(/Users/lihaoyi/.coursier/cache/v1/https/repo1.maven.org/maven2/com/github/scopt/scopt_2.12/3.5.0/scopt_2.12-3.5.0.jar,1478105329000)
(/Library/Java/JavaVirtualMachines/jdk1.8.0_152.jdk/Contents/Home/jre/lib/ext/sunec.jar,1505382645000)
(/Library/Java/JavaVirtualMachines/jdk1.8.0_152.jdk/Contents/Home/jre/lib/ext/nashorn.jar,1505382645000)
(/Library/Java/JavaVirtualMachines/jdk1.8.0_152.jdk/Contents/Home/jre/lib/ext/cldrdata.jar,1505382644000)
(/Library/Java/JavaVirtualMachines/jdk1.8.0_152.jdk/Contents/Home/jre/lib/ext/jfxrt.jar,1505368096000)
(/Library/Java/JavaVirtualMachines/jdk1.8.0_152.jdk/Contents/Home/jre/lib/ext/dnsns.jar,1505382644000)
(/Library/Java/JavaVirtualMachines/jdk1.8.0_152.jdk/Contents/Home/jre/lib/ext/localedata.jar,1505382644000)
(/Library/Java/JavaVirtualMachines/jdk1.8.0_152.jdk/Contents/Home/jre/lib/ext/sunjce_provider.jar,1505382645000)
(/Library/Java/JavaVirtualMachines/jdk1.8.0_152.jdk/Contents/Home/jre/lib/ext/sunpkcs11.jar,1505382645000)
(/Library/Java/JavaVirtualMachines/jdk1.8.0_152.jdk/Contents/Home/jre/lib/ext/jaccess.jar,1505382644000)
(/Library/Java/JavaVirtualMachines/jdk1.8.0_152.jdk/Contents/Home/jre/lib/ext/zipfs.jar,1505382645000)
(/System/Library/Java/Extensions/MRJToolkit.jar,1504544646000)
(/ammonite.predef.interpBridge,-51)
(/ammonite.predef.interpBridge$,91)
(/ammonite.predef.DefaultPredef,11)
(/ammonite.predef.DefaultPredef$,109)
(/ammonite.predef.predefScript,-9)
(/ammonite.predef.predefScript$,126)
(/ammonite.$file.build,127)
(/ammonite.$file.build$,-93)
(/ammonite.$file.build$MyScalaModule,2)
(/ammonite.$file.build$MyScalaModule$MyTests,-19)
(/ammonite.$file.build$demo$,-91)
(/ammonite.$file.build$demo$test$,-7)
```
That means that if you have multiple build scripts which are identical but whose output (e.g. `demo.sources`) depend on the working directory, the output will be cached incorrectly across the build scripts.

Simple solution is to add the current working directly to the cache key. That should bust things.

**Comment by Dennis4b** [comment]
Great, thanks!

This reminded me to ask to clarify: what is actually the policy on running multiple instances of mill?

I imagine running it twice in the same working directory might cause problems, but it would be unexpected if running mill in different paths (projects) would cause problems - but since both instances do share a global cache dir I could imagine it's problematic. Or does mill/ammonite use locks?

**Comment by lihaoyi** [comment]
Bumping Ammonite to https://github.com/lihaoyi/Ammonite/commit/33b728c0d4abd906a5f4e369022fd6c338d6dd07 should fix this.

@Dennis4b we don't have a real policy. 

Running multiple Mill things in parallel in the same repo may stomp over each other, or they may not. Shouldn't be hard to lock things, hopefully at a fine enough grain we don't unnecessarily block parallel Mill commands (this is a big usability problem with Bazel for example)

Running multiple Mill things in separate folders probably won't stomp over each other, once https://github.com/lihaoyi/Ammonite/commit/33b728c0d4abd906a5f4e369022fd6c338d6dd07 goes in at least, since they'll only interact through the ~/.mill/ammonite/cache` folder and should all hash to different cache keys.

One other point of contention is Coursier; that currently shares a global cache. Not sure what it's concurrency semantics are.
