### ISSUE TITLE
Unable to resolve scalaworker behind corporate proxy

### ISSUE THREAD

**Issue by GrannyOlli** [lihaoyi/mill#187]
In ScalaWorkerApi, resolving mill-scalaworker and compiler-interface from hard-coded repo1.maven.org fails behind a corporate proxy. It should be possible to configure a maven proxy for this.

https://github.com/lihaoyi/mill/blob/c5b967515cc4ccf6ebe76c69691c196b55113b3c/scalalib/src/mill/scalalib/ScalaWorkerApi.scala#L21

**Comment by lihaoyi** [comment]
Yeah this is not currently possible, I have a commit in the `test` branch that will expose this as something you can configure

**Comment by lihaoyi** [comment]
@GrannyOlli can you try using the latest unstable version https://github.com/lihaoyi/mill/releases/download/unstable/0.1.3-9-a6bd3d, instantiating a new `mill.scalalib.ScalaWorkerModule` in your `build.sc` with it's `repositories` overriden, and then overriding your `scalaWorker` in your `ScalaModule`s to point towards your custom `mill.scalalib.ScalaWorkerModule`?

**Comment by GrannyOlli** [comment]
Thank you, i will try that!

**Comment by lihaoyi** [comment]
should be doable in 0.1.4
