### ISSUE TITLE
support equivalent of sbt's `scalaJSUseMainModuleInitializer := true` for Scala.js

### ISSUE THREAD

**Issue by bbarker** [lihaoyi/mill#190]
`scalaJSUseMainModuleInitializer := true` avoids the need for extending
`JSApp` (deprecated): https://www.scala-js.org/tutorial/basic/index.html

**Comment by rockjam** [comment]
@bbarker it should be supported out of box without the need for `scalaJSUseMainModuleInitializer` setting

**Comment by bbarker** [comment]
@rockjam @lihaoyi 

Here's a fairly minimal example that seems to demonstrate the issue ([full project here](https://github.com/bbarker/ProjectGists/tree/master/Scala/MillScalaJSExec); with [index.html](https://github.com/bbarker/ProjectGists/blob/master/Scala/MillScalaJSExec/client/static/public/index.html)):

```scala
package io.github.bbarker

import mhtml._
import org.scalajs.dom
import scala.scalajs.js.JSApp
import scala.xml.Node


object Main /*extends JSApp */ {

  val mainDiv: Node = <div>
    Hello world!
  </div>

  //
  //  This works:
  //

  //  def main(): Unit = {
  //    println("Hello from main")
  //    mount(dom.document.body, mainDiv)
  //    ()
  //  }

  def main(args: Array[String]): Unit = {
    println("Hello from main")
    mount(dom.document.body, mainDiv)
    ()
  }
}
```

**Comment by bbarker** [comment]
To be clear, the part that says "this works" only works if `extends JSApp` is uncommented.

**Comment by rockjam** [comment]
What if you specify `def mainClass = Some("io.github.bbarker. Main")` in your build? Will it be the same result?

**Comment by rockjam** [comment]
@bbarker looks like it works without `extends JSApp` when you specify `mainClass`in build
![image](https://user-images.githubusercontent.com/1951244/36939362-a5e11308-1f40-11e8-9dec-09fe3011348c.png)
here is a diff: 

```
diff --git a/Scala/MillScalaJSExec/build.sc b/Scala/MillScalaJSExec/build.sc
index e48c4a0..68cf528 100644
--- a/Scala/MillScalaJSExec/build.sc
+++ b/Scala/MillScalaJSExec/build.sc
@@ -5,8 +5,9 @@ import mill.scalajslib._
 object client extends ScalaJSModule {
   def scalaVersion = "2.12.4"
   def scalaJSVersion = "0.6.22"
+  def mainClass = Some("io.github.bbarker.Main")
   def ivyDeps = Agg(
     ivy"org.scala-js::scalajs-dom::0.9.4",
     ivy"in.nvilla::monadic-html::0.4.0-RC1"
   )
-}
\ No newline at end of file
+}
```

**Comment by rockjam** [comment]
By the way, which version of mill do you use? In latest master branch there is auto-detection of main class for scala.js modules. If you don't use latest master, you should try it 😃

**Comment by bbarker** [comment]
@rockjam aha, I had just added the 0.1.3 version to my dockerfile, since I develop in docker and am weird like that. Maybe I should use mill from the repo directly as you suggest since things are moving quickly these days.

**Comment by rockjam** [comment]
@bbarker try 0.1.4 - it's out now

**Comment by yuanqingfei** [comment]
I used 0.1.6 now. Yes, it can detect standard main class automatically. However, if you still use old style like below.

object ScalaJSExample extends js.JSApp{
  def main() { ...}
}

currently, Mill still can compile successfully since scala.js 0.6.22 still have JSApp object. However, in run time, it will don't output anything which somewhat misleading though.
