### ISSUE TITLE
Please consider renaming to a more easily searchable name

### ISSUE THREAD

**Issue by SRGOM** [lihaoyi/mill#208]

**Comment by SRGOM** [comment]
"Mill rust"

**Comment by rockjam** [comment]
Does "Mill build tool" or "mill scala" give more relevant result?

**Comment by rockjam** [comment]
Both work for mee

**Comment by SRGOM** [comment]
I figured mill was extensible so if I'm looking for building a rust project using mill I'll look for "Mill rust" as the first search term

**Comment by DavidGregory084** [comment]
Mill is a Scala build tool tho :smile:

**Comment by DavidGregory084** [comment]
You're right that there's nothing to stop you building Rust with Mill of course, but I don't imagine we can get great results for every "<build tool name> <programming language>" pair out there

**Comment by lihaoyi** [comment]
The solution here is that you should start publishing blog posts on mill-rust integration to increase our SEO
