### ISSUE TITLE
Option to exclude transitive ivy dependencies

### ISSUE THREAD

**Issue by raskam** [lihaoyi/mill#214]
Currently `Dep` only has an option to configure coursier attributes, but there's no way to configure coursier exclusions.

Right now I'm using implicits to achieve this:

```scala
  implicit class RichDep(dep: Dep) {
    def exclude(exclusions: (String, String)*): Dep = {
      dep match {
        case d: Dep.Java => d.copy(dep = d.dep.copy(exclusions = d.dep.exclusions ++ exclusions))
        case d: Dep.Scala => d.copy(dep = d.dep.copy(exclusions = d.dep.exclusions ++ exclusions))
        case d: Dep.Point => d.copy(dep = d.dep.copy(exclusions = d.dep.exclusions ++ exclusions))
      }
    }
  }
```

And usage:

```
ivy"org.quartz-scheduler:quartz:${V.quartzV}"
  .exclude(
    "com.mchange" -> "c3p0",
    "com.zaxxer" -> "HikariCP-java6"
  )
```

Better would be of course to modify the `Dep` directly. I could make it into PR if you like the way it is implemented.

**Comment by lihaoyi** [comment]
@raskam you can always fall back to passing in a `coursier.Dependency` to `ivyDeps`; could you try configuring one with the exclusion you want and seeing if that works?
