### ISSUE TITLE
mill doesnt response after 0.1.2 on WSL

### ISSUE THREAD

**Issue by seoh** [lihaoyi/mill#225]
I tried to run just single Hello World code. 

// foo/src/Main.scala
```
object Main extends App {
  println("run by mill")
}
```

0.1.0 and 0.1.1 can compile and run. 0.1.2(and after versions) doesnt work but interactive mode works.

![image](https://user-images.githubusercontent.com/2159453/37341066-87c123c0-2703-11e8-9ba2-63913448f6aa.png)

I tried same steps from lastest source(master branch) but still not work as 0.1.2.
Did I miss something to do?

Evironment
- Windows 10 Education 1709
- JDK 1.8.0_151
- Scala 2.12.4

**Comment by lihaoyi** [comment]
Let's consolidate this under https://github.com/lihaoyi/mill/issues/157

**Comment by seoh** [comment]
I saw that issue and is not matched with my situation. I cannot explain my experience properly because of my poor English. I just give up :(
