### ISSUE TITLE
assembly should allow configuring the merge strategy

### ISSUE THREAD

**Issue by gabro** [lihaoyi/mill#233]
The `assembly` task doesn't allow to define a merge strategy for duplicate files across jars. This is needed - for example - for typesafe config `reference.conf` files, which usually need to be concatenated.

This issue doesn't allow me to use Mill on a project which uses akka, because the default akka `reference.conf` is not present in the final jar.

It would be cool for Mill to have a way of defining a merge strategy similarly to how sbt-assembly does it (choose between discard/concat/first/...).

This would also provide an API to do things like #232 in a more principled way.

**Comment by lihaoyi** [comment]
Yeah it probably should

**Comment by mlerner** [comment]
Any progress on this? This would be awesome to have and is actually a blocker to our team migrating off of sbt to `mill`. 

@rockjam: I would would be happy to dig into the code and implement if you are busy

**Comment by rockjam** [comment]
@mlerner I did some prototyping on this one, no PR yet, but I hope to create one in next couple days. You can join that PR and provide your help if needed, how about that?

**Comment by alexarchambault** [comment]
FYI, if that can help, in coursier, there's [some code that generates assemblies](https://github.com/coursier/coursier/blob/5c6d719598ae6300ec90447997e264977c5990d1/cli/src/main/scala-2.12/coursier/cli/util/Assembly.scala#L38), supporting rules (with an example of rules [around here](https://github.com/coursier/coursier/blob/5c6d719598ae6300ec90447997e264977c5990d1/cli/src/main/scala-2.12/coursier/cli/Bootstrap.scala#L228)), which is less than 100 SLOCs… Feel free to copy-paste or get some inspiration from it if you'd like…

**Comment by rockjam** [comment]
@alexarchambault thank you, will take a look
