### ISSUE TITLE
Need include all javascript library automatically

### ISSUE THREAD

**Issue by yuanqingfei** [lihaoyi/mill#237]
Mill seems have no such ability as SBT does. Currently I have to include js library in the html manually. Do we have some plan to generate a all-in-one javascript? Just like in SBT:
 jsDependencies +=  "org.webjars" % "jquery" % "2.1.4" / "2.1.4/jquery.js"

Thanks.

**Comment by lihaoyi** [comment]
We're probably not going to support it directly, though you write some code to do this on your own
