### ISSUE TITLE
How to add scalajs dependency in mill?

### ISSUE THREAD

**Issue by yuanqingfei** [lihaoyi/mill#238]
forgive me if this question is too simple.

Currently I make it work like this:
  def ivyDeps = Agg(
    ivy"org.scala-js::scalajs-dom_sjs${scalaJSBridgeVersion()}:0.9.1",
    ivy"be.doeraene::scalajs-jquery_sjs${scalaJSBridgeVersion()}:0.9.1"
    //ivy"org.webjars:jquery:2.1.4"
  )

but it looks ugly. Anyone know better way or something similar in SBT?
libraryDependencies += "org.scala-js" %%% "scalajs-dom" % "0.9.1"

**Comment by guersam** [comment]
Have you tried `<org>:::<name>:<version>`?

https://github.com/lihaoyi/mill/blob/master/scalajslib/src/mill/scalajslib/ScalaJSModule.scala#L146

**Comment by yuanqingfei** [comment]
Yes, I tried. It only affect scala version from 2.12 to 2.12.4

**Comment by guersam** [comment]
Ok, then how about ` <org>:::<name>::<version>`? (two colons before version) If I read the source code correctly, it'll append the platform-specific cross version suffix to the module name.

**Comment by yuanqingfei** [comment]
Great! it works. Thank you. Guersam!

**Comment by lihaoyi** [comment]
Questions in the gitter room please
