### ISSUE TITLE
Propagate javacOptions in Tests module

### ISSUE THREAD

**Issue by gabro** [lihaoyi/mill#244]
I think it would make sense to propagate the `javacOptions` value of a `ScalaModule` down to its `Tests` module by default.

I've tried to include it in https://github.com/lihaoyi/mill/pull/236, but it resulted in [an obscure CI error](https://travis-ci.org/lihaoyi/mill/jobs/355254688), which I was not able to reproduce on my machine.

I don't have time to work on this, but since I've already spent some time on it without success, I thought it would be beneficial to make future devs aware to my previous attempt.

**Comment by lihaoyi** [comment]
https://github.com/lihaoyi/mill/commit/26865c6623d57b7a5d774c7bbfe5897609e11acf
