### ISSUE TITLE
mill does not honor the custom repositories at global scale

### ISSUE THREAD

**Issue by shengc** [lihaoyi/mill#246]
in `sbt`, I can override the default repositories by setting
```bash
-Dsbt.override.build.repos=true -Dsbt.repository.config=...
```
so I can pass in a list of custom repositories for the entire build. 

For `mill`, although documentation suggests one can override the repositories through the `repositories` task, the initial dependencies needed to boostrap the build are still resolved through the default repositories. 

```bash
[19/26] readapi.compileClasspath
3 targets failed
mill.scalalib.ScalaWorkerModule.classpath
Resolution failed for 1 modules:
--------------------------------------------
  com.lihaoyi:mill-scalaworker_2.12:0.1.6
        not found: /Users/shengc/.ivy2/local/com.lihaoyi/mill-scalaworker_2.12/0.1.6/ivys/ivy.xml
        download error: Caught java.net.UnknownHostException: repo1.maven.org (repo1.maven.org) while downloading https://repo1.maven.org/maven2/com/lihaoyi/mill-scalaworker_2.12/0.1.6/mill-scalaworker_2.12-0.1.6.pom

mill.scalalib.ScalaWorkerModule.compilerInterfaceClasspath
Resolution failed for 1 modules:
--------------------------------------------
  org.scala-sbt:compiler-interface:1.1.0
        not found: /Users/shengc/.ivy2/local/org.scala-sbt/compiler-interface/1.1.0/ivys/ivy.xml
        download error: Caught java.net.UnknownHostException: repo1.maven.org (repo1.maven.org) while downloading https://repo1.maven.org/maven2/org/scala-sbt/compiler-interface/1.1.0/compiler-interface-1.1.0.pom
```

I am behind a proxy, so in order to adopt `mill` for my work, I need a way to configure the repositories globally just like `sbt` does.

**Comment by lihaoyi** [comment]
@shengc can you try following the instructions [here](https://github.com/lihaoyi/mill/issues/187#issuecomment-370108695)? That should let it work, and if it works for you help me add it to the documentation somewhere :)

**Comment by shengc** [comment]
@lihaoyi yep that works. I can send a PR to update Readme.md after hours.

**Comment by shengc** [comment]
@lihaoyi for `import $ivy`, the custom repositories still does not work. The following can download the dependencies

```scala
interp.repositories() ++= Seq(...)
interp.load.ivy(...)
```

However, the downloaded dependencies are not added to the build.

**Comment by shengc** [comment]
@lihaoyi if I pass in the revolvers through `--predef` to `mill`, then `import $ivy...` works. Is there any initialization misconfiguration lurked in the code ?
