### ISSUE TITLE
Add a fullOpt version of ScalaJSModule#run

### ISSUE THREAD

**Issue by lihaoyi** [lihaoyi/mill#249]
Not hard, just need to copy what we did for the `fastOpt` version of `run`
```scala
    def run(args: String*) = T.command {
      finalMainClassOpt() match{
        case Left(err) => mill.eval.Result.Failure(err)
        case Right(_) =>
          ScalaJSBridge.scalaJSBridge().run(
            toolsClasspath().map(_.path),
            nodeJSConfig(),
            fullOpt().path.toIO
          )
          mill.eval.Result.Success(())
      }

    }
```

**Comment by ror6ax** [comment]
Because method and parameter are the same, I don't suppose we can just copy the method. Did you mean something like renaming run to runfullopt and runfastopt? Or some conditional based on args?

**Comment by lihaoyi** [comment]
https://github.com/lihaoyi/mill/commit/55ec0b9532c6dabecd8816099a7f072711624397
