### ISSUE TITLE
mill does not stop running processes when ctrl+c

### ISSUE THREAD

**Issue by antonkulaga** [lihaoyi/mill#258]
When I run any server-like application with Mill (like https://github.com/siddhartha-gadgil/MillScalaServer ) by 
```bash
 mill server.run
```
and then do CTRL+C to go out of Mill, it does NOT close the app that is running (at least on Linux Mint/Ubuntu). In fact in the console it says "[1]+  Stopped                 mill server.run" but in reality localhost:8080 still loads the akka-http app.

**Comment by lihaoyi** [comment]
@antonkulaga maybe try `mill server.runLocal` for now? Mill forks by default and I'm not sure how easy it would be to make it close down child processes when it dies

**Comment by antonkulaga** [comment]
@lihaoyi server.runLocal has similar problem :( Often it does not stop akka-http app (esp. if several pages are loaded in the browser) when CTRL+C

**Comment by antonkulaga** [comment]
Looks like runLocal and CTRL+C does not stop mill process and after some time of running/stopping/editing/compiling/running I get more than 5 and have to kill them manually.

**Comment by antonkulaga** [comment]
Here is what I often have after several runLocal and CTRL+C
![mill_processes](https://user-images.githubusercontent.com/842436/38278037-27cf6066-37a3-11e8-833a-348cb5b58b3a.png)

**Comment by lihaoyi** [comment]
@antonkulaga could you also try `mill -i server.run`? I think that or `mill -i server.runLocal` should be a workaround for the problem

**Comment by antonkulaga** [comment]
@lihaoyi  I think I already answered that it did not work unless you fixed something really recently

**Comment by lihaoyi** [comment]
@antonkulaga previously the commands I suggested didn't have the `-i` flag in them; could you try the same commands with `-i` enabled?

**Comment by zartstrom** [comment]
I have the same issue (process not killed after CTRL+C) with a simple Finch HTTP server, but `mill app.runLocal` does help (even without the `-i` flag). I'm on mill 0.2.2.

**Comment by lihaoyi** [comment]
Fixed in 0.2.5
