### ISSUE TITLE
Support forked execution for ScalaModule#run and TestScalaModule#test

### ISSUE THREAD

**Issue by lihaoyi** [lihaoyi/mill#27]
Currently, `ScalaModule#run` runs in a subprocess and `TestScalaModule#test` runs in-process in a Classloader. This is arbitrary and inconsistent

We should standardize on a way to let either method run either subprocessed or in-process, and make this available to the user of Mill if they want to run any arbitrary JVM classpath as part of any task.

**Comment by alexarchambault** [comment]
Now that mill is public, I donn't mind if anyone want to take a cut at that…

**Comment by alexarchambault** [comment]
(I don't think I didn't remove the assignment myself, but that doesn't matter…)
