### ISSUE TITLE
Built-in task to show mill version

### ISSUE THREAD

**Issue by rockjam** [lihaoyi/mill#276]
There should be some embedded task to check mill's version. We could implement it as ExternalModule, available for all mill users like GenIdea module.

How to find out mill's version:
```
def millVersion() = T {
  System.getProperty("MILL_VERSION")
}
```

**Comment by lihaoyi** [comment]
`version` should probably be a built in task on `MainModule` rather than an `ExternalModule`, given it's so simple

**Comment by lihaoyi** [comment]
https://github.com/lihaoyi/mill/commit/36eb8bd6bfd534d002b01f8800e4b5d896aa4e77
