### ISSUE TITLE
Small suggestion on the decription text 'Your shiny new Scala build tool'

### ISSUE THREAD

**Issue by ugoa** [lihaoyi/mill#280]
Maybe it's just me, but the phrase `Your shiny new Scala build tool` makes `mill` sound like a toy project and it's just being developed for fun. 
For me I am really looking forward to this tool going mature and eventually becoming a competitive replacement of `sbt`, so maybe the word can be less dramatic and point out some real advantages of mill over sbt. It would be great for devs to **really** try it out and give feedbacks/PRs. Just my two cents. Cheers

**Comment by lihaoyi** [comment]
Let's continue this discussion in gitter
