### ISSUE TITLE
Current release cannot build master

### ISSUE THREAD

**Issue by grebe** [lihaoyi/mill#293]
I get the following error message when I run `mill main.test`

```
build.sc:67: object creation impossible, since method scalaVersion in trait ScalaModule of type => mill.T[String] is not defined
object client extends MillPublishModule{
       ^
build.sc:74: object creation impossible, since method scalaVersion in trait ScalaModule of type => mill.T[String] is not defined
object testng extends MillPublishModule{
       ^
Compilation Failed
```

I'm using the release on homebrew (0.1.7) which seems to match the latest release on github. Am I doing something dumb? Is there some other way to bootstrap mill?

**Comment by rockjam** [comment]
@grebe This is known issue, it should not be this way. But you can build mill from sources with mill version `0.1.7-77-44ed2e` and above. Manual installation is described here: http://www.lihaoyi.com/mill/#manual

**Comment by lihaoyi** [comment]
I think it's not unreasonable to say "to build master, use the latest unstable release". Mill is probably going to need to re-bootstrap off recent unstable releases reasonably often as it evolves, and if we require bootstrapping off stable versions we'd just end up with a ton of tiny, meaningless stable versions.

CI will ensure that there's always *some* version of Mill that can bootstrap the current master. Hopefully the latest unstable version can do it too, though that's not enforced.

If you could update the docs so people know to bootstrap off the unstable release that would help
