### ISSUE TITLE
Documentation about remote binary dependencies

### ISSUE THREAD

**Issue by woky** [lihaoyi/mill#300]
There's no mention in documentation about adding remote third party dependencies (The Maven/Ivy ones). In some `build.sc` files I found on GitHub there's `def ivyDeps`. For newcomers like me, that's not intuitive. The documentation seem to focus only on command-line usage instead of writing the build files.

In SBT there's https://www.scala-sbt.org/1.x/docs/Library-Dependencies.html#Managed+Dependencies

**Comment by francisdb** [comment]
Are you looking for this?
http://www.lihaoyi.com/mill/page/configuring-mill.html#adding-ivy-dependencies

I personally am not a fan of this `ivy` everywhere but the docs are there

**Comment by woky** [comment]
Yeah that's it. Sorry, I missed that.
