### ISSUE TITLE
More flexible query language for running multiple tasks

### ISSUE THREAD

**Issue by lihaoyi** [lihaoyi/mill#31]
Currently running multiple tasks in Mill is a bit of a pain:

```bash
mill run Core.test && mill run ScalaPlugin.test
```

Even though the second task will benefit from caching of the first, the tasks run sequentially. Mill's execution engine is actually happy to evaluate multiple tasks in parallel, we just need to expose it to the user.

uTest has a similar problem (users want to select multiple paths of tests to run) and allows syntax like:

```
testOnly -- test.examples.NestedTests.outer1.{inner1,inner2}
testOnly -- test.examples.NestedTests.{outer1.inner1,outer2.inner3}
testOnly -- {test.examples.HelloTests.test1,test.examples.NestedTests.outer2}
``` 

We could copy that, but we'd probably also want more flexibility, e.g. 

```bash
mill run {Core,ScalaPlugin}.test
# Run all tasks ending in `.test`; might need to pick a different syntax for bash-compatibility
mill run *.test 
```

Notably, whatever syntax we choose should be able to play nicely with tasks taking command-line arguments

```bash
mill run Core.test mill.define.ApplicativeTests
```

And hopefully we'll be able to find something with less awkward quoting than SBT's 
```bash
sbt "core/testOnly -- mill.define.ApplicativeTests"
```

**Comment by rockjam** [comment]
@lihaoyi do we want to allow syntax like this to run tasks `outer.inner1.compile` and `outer.inner2.compile`
`mill outer.{inner1, inner2}.compile`

**Comment by rockjam** [comment]
> # Run all tasks ending in `.test`; might need to pick a different syntax for bash-compatibility
> mill run *.test 

Regarding syntax to run all tasks ending with `.test` we could use underscore instead of *. It will be 
```
mill _.test
```
what do you think?

**Comment by lihaoyi** [comment]
Yeah `mill outer.{inner1, inner2}.compile` seems reasonable. Using `_` for `_.test` seems like a good idea as well
