### ISSUE TITLE
Generated Intellij project: output path is shared between production, tests

### ISSUE THREAD

**Issue by guilgaly** [lihaoyi/mill#311]
I have created a mill build with a few modules, each of them with a nested test module. I have generated and opened an Intellij IDEA project with `mill.scalalib.GenIdea/idea`. If I try to run anything from within IDEA (rather than from mill), I get the following error for each test module :
```
Output path <project path>/out/myModule/test/compile/dest/classes is shared between: Module 'myModule.test' production, Module 'myModule.test' tests
```

This is apparently because the test modules have an output path, but don't have a test output path. Since mill test modules only contain test code, I solved this by removing the regular output path, and using the same path for the test output path instead (basically, replace `<output>` with `<output-test>`). It seems to work for me.

I'll make a PR for this (it seems like it would be a trivial change in `GenIdeaImpl`), hopefully I'm not missing something obvious here.

**Comment by guilgaly** [comment]
I did some more tests; I also think that the `resources` folder in a test module should be declared as:
```<sourceFolder url="file://$MODULE_DIR$/../myModule/test/resources" type="java-test-resource" />```
And not:
```<sourceFolder url="file://$MODULE_DIR$/../myModule/test/resources" isTestSource="true" type="java-resource"/>```

The first one is what I get if I manually set the path for "test resources" in IDEA; the latter is just seen as "resources" after opening in IDEA.

**Comment by rockjam** [comment]
@guilgaly I guess we can close this?

**Comment by guilgaly** [comment]
@rockjam sure, fine with me. 👍
