### ISSUE TITLE
Port sbt-updates to mill

### ISSUE THREAD

**Issue by guilgaly** [lihaoyi/mill#314]
The [sbt-updates plugin](https://github.com/rtimush/sbt-updates) allows to check if there are newer versions available for a project's dependencies (from the project's configured Maven and Ivy repos). It should be pretty straightforward to reuse a lot of code from the SBT plugin (all the logic for understanding and comparing version numbers isn't SBT-specific and is licensed under BSD 3-clause).

I can try to do it when I have some time, if it's OK to submit this for the main mill repo (otherwise we can close this issue and I'll try to do something similar to [mill-dgraph](https://github.com/ajrnz/mill-dgraph)).

**Comment by rockjam** [comment]
Sound good to me to have it in mill main repo. Maybe coursier have a functionality to check for newer version, I don't know for sure

**Comment by guilgaly** [comment]
I'll definitely check that out, but I don't expect so, since "newer" is a bit subjective (as Maven/Ivy don't really enforce a versioning scheme)... In practice, sbt-updates just tries to parse the version string against a bunch of known versioning schemes (like semver) and ignores anything it doesn't understand.

But even if we could just use coursier to resolve available versions, that would already be nice (sbt-updates does its own thing to download artefact metadata and parse the list of available versions). Anyway, I'll see what I can find.

**Comment by alexarchambault** [comment]
Yeah, there's some basic stuff for that in coursier, around [here](https://github.com/coursier/coursier/blob/8427be2d453581b86e6b3aae8c581e6521e90e12/core/shared/src/main/scala/coursier/maven/MavenRepository.scala#L160) for Maven repositories, and [here](https://github.com/coursier/coursier/blob/8427be2d453581b86e6b3aae8c581e6521e90e12/core/shared/src/main/scala/coursier/ivy/IvyRepository.scala#L171) for Ivy repositories (although just Maven should cover most cases for mill).

The Maven method could be made public, and its signature possibly added to `coursier.core.Repository` (and be later implemented for other repos…). It's tested indirectly in coursier by resolving versions like `x.y.+` around [here](https://github.com/coursier/coursier/blob/8427be2d453581b86e6b3aae8c581e6521e90e12/tests/shared/src/test/scala/coursier/test/CentralTests.scala#L383).

Send a PR to do that in coursier if you'd like, and I'll do a release right after it…

**Comment by guilgaly** [comment]
@alexarchambault Thanks, I'll have a look!

**Comment by lihaoyi** [comment]
+1 this sounds like something simple & useful enough to be worth including as part of Mill

**Comment by antonkulaga** [comment]
Yeah, I really miss sbt-updates!
