### ISSUE TITLE
mill version should work without build file

### ISSUE THREAD

**Issue by francisdb** [lihaoyi/mill#328]
if there is no build.sc

```
 ~ mill version
Compiling (synthetic)/ammonite/predef/interpBridge.sc
Script file not found: /Users/francisdb/build.sc
```

within project

```
mill version
[1/1] version
0.2.0
```

was introduced here: https://github.com/lihaoyi/mill/issues/276

**Comment by lihaoyi** [comment]
This should be the case in master, try the latest unstable executable
