### ISSUE TITLE
Appveyor/Windows tests are flaky

### ISSUE THREAD

**Issue by lihaoyi** [lihaoyi/mill#341]
They seem to hang at arbitrary points before timing out at the 1hr mark.

Looking through the test history, the first such flake is at 

- https://ci.appveyor.com/project/lihaoyi/mill/build/1.0.464
- https://github.com/lihaoyi/mill/pull/309

Which seems entirely benign and unlikely to cause such behavior. Since then it seems to have gotten even less stable...

@robby-phd any ideas what could be going wrong?

**Comment by robby-phd** [comment]
Closing this as AppVeyor seems ok now.
