### ISSUE TITLE
Allow to configure the TwirlCompiler

### ISSUE THREAD

**Issue by Mogztter** [lihaoyi/mill#350]
Currently it's not possible to override these settings:

* additionalImports
* constructorAnnotations
* codec
* inclusiveDot

The reason is that we are using reflection to call the method `compile` and this method is using default values: 
https://github.com/playframework/twirl/blob/2f928ec6b245ef235a2bdbbd109df48bbf5463c5/compiler/src/main/scala/play/twirl/compiler/TwirlCompiler.scala#L167

To workaround around this issue we can:

* Call the Java API (introduced in Twirl 1.3.1): https://github.com/playframework/twirl/blob/1.3.1/compiler/src/main/java/play/japi/twirl/compiler/TwirlCompiler.java
* Introduce a new Scala `compile` method in Twirl that does not use default values (ask the twirl team + create a pull request). But if the only reason is to call the method via reflection why not use the Java API ?

I do have two more ideas to workaround this issue but those are bad ideas 😉 
If you do have a better idea, feel free to comment.

I think using the Java API is probably the safest choice, the only downside is that the TwirlCompiler will only work with version 1.3.1 or newer...

**Comment by lihaoyi** [comment]
This seems to have happened in https://github.com/lihaoyi/mill/pull/473

**Comment by Mogztter** [comment]
Oh wow thanks @yurique

**Comment by yurique** [comment]
Well, in that PR only the default+additional imports were addresses :)

I've never used these:

* constructorAnnotations
* inclusiveDot

and have no idea what they do. Are those useful/often-used?

**Comment by Mogztter** [comment]
> I've never used these:
constructorAnnotations
inclusiveDot
and have no idea what they do. Are those useful/often-used?

Me neither... though I primarily use Twirl Templates in Play! application... maybe it can be useful in some other contexts.
Having said that, now that you did the hard work, it should be easy to add `constructorAnnotations` and `inclusiveDot` ?

**Comment by yurique** [comment]
@Mogztter, 
I'll make a PR today

**Comment by yurique** [comment]
And here it is:
https://github.com/lihaoyi/mill/pull/481

The inclusive dot is doing something weird - I don't understand it :) - it appends `$$TwirlInclusiveDot` to the class/object names and puts it into the file names.
