### ISSUE TITLE
GenIdea does not trigger target recomputation

### ISSUE THREAD

**Issue by Baccata** [lihaoyi/mill#352]
I found it whilst testing https://github.com/lihaoyi/mill/pull/351, and found that I had to call upon `mill __.ivyDeps` after adding/removing dependencies to my modules in order for the idea config to be generated appropriately. 

Steps to reproduce : 
* Generate idea config from mill  
* Add/remove an arbitrary ivy dependency to one module 
* Regenerate idea config (without running any other mill command after previous step) 
* Look at cache in `/out/module/ivyDeps` to check whether the dependency was indeed added/removed

**Comment by raskam** [comment]
In my case calling `mill __.ivyDeps` is not sufficient and I always have to remove `out` directory before running `mill mill.scalalib.GenIdea/idea`.

I also have to reopen the project in Idea, because sometimes Idea would still use old classpath.
