### ISSUE TITLE
Equivalent withSources() withJavadoc()

### ISSUE THREAD

**Issue by hmf** [lihaoyi/mill#356]
I would like to download the sources and docs and have them accessible via the IntelliJ IDE. 
In SBT I would use `withSources()` and `withJavadoc()` in the dependencies declaration. What is the equivalent in MILL. 

TIA

**Comment by rockjam** [comment]
Currently, there is no such API exposed externally, but `mill mill.scalalib.GenIdea/idea` downloads external dependencies with sources by default

**Comment by hmf** [comment]
Does not seem to do this because when I access the class IJ warns me that no sources were found and that what it shows has been decompiled. Looking at the external jars, I see no sources. Maybe not the default? If so, is their a switch?

**Comment by rockjam** [comment]
It is a default, this behavior is defined right here: https://github.com/lihaoyi/mill/blob/cb327ee2f04a5493d285b4e4dd04a89c96b7c23c/scalalib/src/mill/scalalib/GenIdeaImpl.scala#L96

I tried my own project and checked `mill mill.scalalib.GenIdea/idea` - it downloads and attaches sources to idea project definition. 
What version of mill do you use?
Which of your libraries doesn't have sources - can you give an example?

**Comment by hmf** [comment]
Using the latest version 0.2.2.
 
Ok, I I can see the sources jars in the external libraries folder. Don't know why I missed them before. Not all sources are there so I assume this is because they were not published.
 
Went back and right-clicked on the definition and got the same de-compile message.  I can "attach" the source and this works. I had assumed that the IDE would pick these up automatically. Is the manual set-up the correct way to go?

Thanks for the help.

**Comment by rockjam** [comment]
> Went back and right-clicked on the definition and got the same de-compile message. I can "attach" the source and this works. I had assumed that the IDE would pick these up automatically. Is the manual set-up the correct way to go?

I remember the same behavior in sbt projects in Intellij Idea too. It happens sometimes

**Comment by hmf** [comment]
Thanks @rockjam
