### ISSUE TITLE
Add `T.source` or make `T.sources` able to watch single files

### ISSUE THREAD

**Issue by MikaelMayer** [lihaoyi/mill#360]
After browsing the code and using Mill on a non-Scala project, I figured out that if I give a single file to `T.sources`, its modifications are ignored. I am watching a particular file because we need to execute a python script every time this file changes.

I ended up writing:

    def examplesTemplates = T.input { (pwd / 'src / "ExamplesTemplates.elm").toNIO.toFile.lastModified() }

It would be nice if the above could simply be written:

    def examplesTemplates = T.source { pwd / 'src / "ExamplesTemplates.elm" }

or alternatively, make `T.sources` detect that it is a file and watch its timestamp instead.

**Comment by jkstrauss** [comment]
@MikaelMayer I made a simple test branch to demonstrate using T.sources with a single file, and it seems to work. Please checkout (https://github.com/jkstrauss/mill/tree/sourcesSingle), and see if you can reproduce the problem.

Make sure the working directory is `scratch`.

This is what I am getting using `--watch` and `touch`ing the source file, so it looks like everything is working as you want it.

     jkstrauss@LAPTOP-0BT4PD8T MINGW64 ~/Documents/mill/scratch (sourcesSingle)
     $ mill --watch show test.abc
     [1/1] show
     [1/1] test.abc
     [
         "ref:8780b0b2:C:\\Users\\jkstrauss\\Documents\\mill\\scratch\\test\\abc"
     ]
     Watching for changes to 3 files... (Ctrl-C to exit)
     [1/1] show
     [1/1] test.abc
     [
         "ref:8780b0b2:C:\\Users\\jkstrauss\\Documents\\mill\\scratch\\test\\abc"
     ]
     Watching for changes to 3 files... (Ctrl-C to exit)
     [1/1] show
     [1/1] test.abc
     [
         "ref:8780b0b2:C:\\Users\\jkstrauss\\Documents\\mill\\scratch\\test\\abc"
     ]
     Watching for changes to 3 files... (Ctrl-C to exit)

**Comment by MikaelMayer** [comment]
I re-tested `T.sources` on a single file and now it works.
I don't know what used to go wrong at the time.
Thanks for reporting that it works.
