### ISSUE TITLE
Request: --watch mode should try to gracefully kill running apps, sbt-revolver style

### ISSUE THREAD

**Issue by megri** [lihaoyi/mill#373]
I had a look at this some time back but felt it was too involved for me to come up with a good solution.

Basically the watcher is blocking a thread which prevents—or so it seemed to me at least—any detection and termination of the ongoing process, from the context where the process handle is available.

**Comment by lihaoyi** [comment]
https://github.com/lihaoyi/mill/commit/57f4968e8c37c857e4c8d6cac80dca739186754d implements `JavaModule#runBackground`, which runs something in the background and only kills it the next time you call `runBackground` on the same module

**Comment by lihaoyi** [comment]
Fixed in 0.2.5
