### ISSUE TITLE
Mill doesn't seem to work on Windows when the user's name starts with lowercase u

### ISSUE THREAD

**Issue by AndyDagnall** [lihaoyi/mill#378]
There seems to be a problem caused by the fact that slash-u starts a Unicode escape sequence.
Here is a screen-grab:
![mill in cygwin screenshot](https://user-images.githubusercontent.com/40645623/42002262-89755084-7a5e-11e8-9ec1-20b695804756.png)

**Comment by lihaoyi** [comment]
This should be easy to fix using `pprint.apply(s: String)` rather than leaning on triple quotes :) if anyone wants to send a PR this is an easy one!
