### ISSUE TITLE
Assembly should not include scala sources & scaladoc

### ISSUE THREAD

**Issue by raskam** [lihaoyi/mill#382]
Final fatjar now contains sources and scaladoc files of project dependencies which in my case increase fatjar size several times.

As a quick workaround I've used the following, but it's obviously not correct as it might exclude also files from resources that we want to keep in the final fatjar.

```
def assemblyRules = Assembly.defaultRules ++ Seq(
  Assembly.Rule.ExcludePattern(""".*\.scala"""),
  Assembly.Rule.ExcludePattern(""".*\.html"""),
)
```

**Comment by lihaoyi** [comment]
I'm not seeing it

```bash
lihaoyi sjsonnet$ mill sjsonnet.assembly
[6/33] sjsonnet.sources
lihaoyi sjsonnet$ jar tf out/sjsonnet/assembly/dest/out.jar  | grep \\.scala
lihaoyi sjsonnet$ jar tf out/sjsonnet/assembly/dest/out.jar  | grep \\.html
org/python/icu/text/package.html
license.html
org/python/icu/math/package.html
org/python/icu/impl/data/package.html
org/python/icu/lang/package.html
org/python/icu/util/package.html
```

Maybe you have something configured in a funny way?

**Comment by raskam** [comment]
Closing, this was caused by incorrectly published libraries by SBT (bug https://github.com/sbt/sbt/issues/3784). Sources + scaladoc were published in a `compile` ivy config, therefore all 3 jars were handled as scala code by Coursier and later by Mill.

**Comment by raskam** [comment]
For future readers: If you use SBT 1.x to publish your libraries to ivy (e.g. `sbt publishLocal` uses ivy) then those published libraries won't work properly with Mill, SBT<0.13.17 and possibly other tools.

What does not work as expected
- fatjars contain javadoc + scala sources
- GenIdea generates Idea project with javadoc marked as Scala sources, which breaks some Idea functionality (autocompletion etc)

As a quick workaround, use SBT 0.13.x to publish your libraries.
