### ISSUE TITLE
SbtModule: really SBT-compatible?

### ISSUE THREAD

**Issue by carueda** [lihaoyi/mill#385]
Per [the documentation](http://www.lihaoyi.com/mill/page/common-project-layouts.html#sbt-compatible-modules), SbtModule allows to:

> follow the SBT project layout:
> ```
> build.sc
> foo/
>   src/
>     main/
>       scala/
>     test/
>       scala/
> ```

However, typically the existing SBT-based structure is:
> ```
> build.sc
> src/
>   main/
>     scala/
>   test/
>     scala/
> ```

That is, with `src/` at first level under the project directory.

Looking at gitter it seems this has in fact created some confusion.  Can the status of SbtModule be clarified please? Thanks!

**Comment by DavidGregory084** [comment]
That is the difference between the layout of a single module SBT project and a multi module layout. See the [SBT documentation](https://www.scala-sbt.org/1.x/docs/Multi-Project.html) for examples. It seems Mill supports the multi module layout because it is more flexible.

**Comment by carueda** [comment]
OK! thanks

**Comment by manuzhang** [comment]
Does it mean Mill doesn't support single module layout ?

**Comment by lefou** [comment]
Mill does not support SBT-style single module layout out of the box. But you can tweak the `millSourcePath` to achieve the same layout.
