### ISSUE TITLE
Warnings coming from the compilation of the compiler bridge should be silenced

### ISSUE THREAD

**Issue by smarter** [lihaoyi/mill#388]
Compiling the compiler bridge can produce warnings (to reproduce, first delete the cached one: `rm -rf out/mill/scalalib/ScalaWorkerModule/worker/dest/2.12.6/compiled/`):
```scala
Compiling compiler interface...
warning: there was one deprecation warning (since 2.11.0)
warning: there were four deprecation warnings (since 2.12.0)
warning: there were 5 deprecation warnings in total; re-run with -deprecation for details
warning: there were three feature warnings; re-run with -feature for details
four warnings found
```
These warnings should be silenced just like in sbt since there is nothing the user can do about them.

**Comment by lihaoyi** [comment]
Fixed in https://github.com/lihaoyi/mill/commit/427966a07b19f388704b97ec8dc33e57af8fbfca
