### ISSUE TITLE
Do not compile hidden files

### ISSUE THREAD

**Issue by smarter** [lihaoyi/mill#402]
If a file starts with a `.`, it shouldn't be compiled, even if it ends with `.scala`. This matches the behavior of sbt and is pretty important for correctness since emacs likes to create backup files `.#Foo.scala`.

**Comment by vic** [comment]
A [workaround](https://gitter.im/lihaoyi/mill?at=5ad6cd801130fe3d36eb7655) currently is to ignore the those temporary files by adding something like the following to your module:

```scala
override def allSourceFiles = super.allSourceFiles().filter(!_.toString.contains('#'))
```

**Comment by jkstrauss** [comment]
I would be willing to work on this for a permanent solution. Do we have a consensus that ignoring hidden files is a reasonable default?

**Comment by smarter** [comment]
While you're at it, I think we should drop hidden files from assembly too: https://github.com/lihaoyi/mill/issues/383#issuecomment-410523802
