### ISSUE TITLE
Change path serialization format

### ISSUE THREAD

**Issue by rockjam** [lihaoyi/mill#426]
Currently, path ref serializes to the following string:
```
"ref:32449fe9:/Users/rockjam/projects/mill/out/dev/assembly/dest/mill"
```
but sometimes it's useful to use a result of the task that returns path. For instance:
`mill root.assembly | xargs -I {} cp {} ~/dist/out.jar`

Is it okay if we change a path ref format to the following one, so we can use json tools to parse output?
```
{
  "path": "/Users/rockjam/projects/mill/out/dev/assembly/dest/mill",
  "quick": true,
  "sig": "32449fe9"
}
```

**Comment by lihaoyi** [comment]
I think we should stick with the current syntax; I explicitly changed it to the current syntax from the proposed syntax a while ago.

While JSON parsing output is convenient, human readability is important too, and using the proposed syntax makes the output take 5x as many lines and commands like `allSources` or `compileClasspath` impossible to skim visually.

**Comment by rockjam** [comment]
I understand the motivation. One more thing - current output format isn't convenient to copy-paste either. If it was a simple path, starting with `/`, I would double click the output string in terminal and paste right there, but in current the format I have to select some part of the path, or copy the whole thing and clean out all before `/`. It's a small thing, but useful(for me at least)

**Comment by lefou** [comment]
What about adding a blank after the colon?
