### ISSUE TITLE
Escape characters for e.g. colors not handled properly for dumb terminals

### ISSUE THREAD

**Issue by bbarker** [lihaoyi/mill#436]
This results in output sort of like this:

```
$ mill api[2.12.6].compile
[34m[5/26] api[2.12.6].sources.overriden.mill.scalalib.MavenModule.sources [39m
[1A[2K[9999D[34m[6/26] api[2.12.6].sources [39m
[1A[2K[9999D[34m[13/26] api[2.12.6].resources [39m
```

Since I'm probably using a dumb terminal from time to time, I wouldn't mind trying to take a stab at this, but pointers welcome.

Currently known `TERM` values that should be supported are `dumb` and `win`.

**Comment by bbarker** [comment]
It looks like there is a `--color` option, but when I use it, I don't see *any* output; it seems that output isn't generated as I would expect either as `out` is sparsely populated compared to usual; compare:

```
$ mill --color api[2.12.6].compile
$ mill  api[2.12.6].compile
[34m[5/26] api[2.12.6].sources.overriden.mill.scalalib.MavenModule.sources [39m
[1A[2K[9999D[34m[6/26] api[2.12.6].sources [39m
[1A[2K[9999D[34m[13/26] api[2.12.6].resources [39m
$ 
```

At least, once this step is addressed, it should be relatively simple to detect `$TERM` and route it to the appropriate configuration.

**Comment by bbarker** [comment]
`mill -i` seems to exit prematurely when given `--color` as well.

**Comment by lihaoyi** [comment]
```scala
$ mill -i --color false
Loading...
@ 1 + 1
res0: Int = 2
```
?

**Comment by bbarker** [comment]
```
$ mill -i --color false
Loading...
Compiling /home/brandon/workspace/ced2ar-api/build.sc
Compiling /home/brandon/workspace/ced2ar-api/(console)
[9999D[0J@  [9999D[2C

[9999D[0J@  [9999D[2Ccompile
[9999D[0J@ compile [9999D[7C[2C
cmd0.sc:1: not found: value compile
val res0 = compile
           ^
Compilation Failed
```

**Comment by lefou** [comment]
Is this fixed?
