### ISSUE TITLE
Why is the default folder layout different from Maven/SBT?

### ISSUE THREAD

**Issue by argv-minus-one** [lihaoyi/mill#443]
I notice that Mill defines its own folder layout for Java/Scala projects (in `JavaModule`), and although [the folder layout conventionally used in Java/Scala projects](https://maven.apache.org/guides/introduction/introduction-to-the-standard-directory-layout.html) can be used by extending `MavenModule`, that is not the default. Mill's documentation [describes its preferred folder layout](http://www.lihaoyi.com/mill/index.html#getting-started), but doesn't seem to explain *why* that's preferred over the Maven layout.

**Comment by lihaoyi** [comment]
This is not an issue; discussion goes in the gitter channel
