### ISSUE TITLE
Weird behavior with abstract class arguments

### ISSUE THREAD

**Issue by jackkoenig** [lihaoyi/mill#448]
New to mill so apologies if I'm just being stupid, but I have observed some strange behavior. Given the following `build.sc`

```scala
import mill._
import scalalib._

object foo extends FooModule("2.12.4")

// I'm just using version as an example, my real case is optional Ivy dependencies
// Behavior is identical even if version is a val
abstract class FooModule(version: String) extends ScalaModule {
  def scalaVersion = version
}
```

And some trivial `foo/src/Main.scala`:
```scala
package foo
object Main extends App {
  println("Hello World!")
}
```

`foo` is not detected as a Module by `mill`, but `FooModule` is:
```
$ mill resolve _
[1/1] resolve 
FooModule
all
clean
inspect
path
plan
resolve
show
version
visualize
visualizePlan
```

Is this intended behavior?

**Comment by julianmichael** [comment]
More details: running `mill show FooModule.scalaVersion` prints `"2.12.4"`, so this seems that mill sees `foo` but gives it the wrong name. Furthermore, add `object foo2 extends FooModule("2.12.6")` and `mill resolve _` prints `FooModule` twice, while running `mill show FooModule.scalaVersion` still prints `"2.12.4"`.

**Comment by lihaoyi** [comment]
This is somewhat intended; in general, you should avoid abstract/non-abstract classes and stick to traits. If you want to use abstract/non-abstract classes, there's some fiddliness with the implementation details that's somewhat unavoidable
