### ISSUE TITLE
caching unmanagedClasspath?

### ISSUE THREAD

**Issue by raould** [lihaoyi/mill#453]
```
  def unmanagedClasspath = T {
     if (!ammonite.ops.exists(millSourcePath / "lib")) Agg()
     else Agg.from(ammonite.ops.ls(millSourcePath / "lib").map(PathRef(_)))
   }
```
but
```
 mill --color false show foo.unmanagedClasspath
```
shows not all the files that i have in lib/, only 6 out of the 61 that are in there. Is there some kind of caching of the directory listing that is happening? I mean sure enough if I "rm -rf ~/.mill" then run the show again, I see all the files that were in lib/. 

While I guess there's some sort of internal logic to it all, it was a poor UX for a/this newcomer to mill.

**Comment by lihaoyi** [comment]
Not enough information to reproduce unfortunately...
