### ISSUE TITLE
expand on the ivyDeps documentation

### ISSUE THREAD

**Issue by raould** [lihaoyi/mill#455]
I don't really understand it enough yet from the examples. I am trying to get it working with bintray so I can use JME3, for example. The Mill docs end up saying to go read the Ammonite docs, which is a link to some stuff that doesn't syntactically look like what was in build.sc, so it pretty much looks like a dead-end to a new user afaict.

**Comment by raould** [comment]
If anybody else cares, here's what ended up (apparently) working for me for using jmonkeyengine with mill:

```
 import mill._, scalalib._
 import coursier.maven.MavenRepository

 object x extends ScalaModule {
   def scalaVersion = "2.12.4"
   def repositories = super.repositories ++ Seq(
     MavenRepository("http://dl.bintray.com/jmonkeyengine/org.jmonkeyengine")
   )
   def ivyDeps = Agg(
     ivy"org.jmonkeyengine:jme3-core:3.2.1-stable",
     ivy"org.jmonkeyengine:jme3-desktop:3.2.1-stable",
     ivy"org.jmonkeyengine:jme3-lwjgl3:3.2.1-stable",
   )
 }
```

**Comment by lihaoyi** [comment]
Questions and discussion belong on gitter
