### ISSUE TITLE
--color false should affect zinc as well 

### ISSUE THREAD

**Issue by raould** [lihaoyi/mill#457]
i am guessing the escape character stuff i am seeing is supposed to be some kind of coloring? 

cd ~/Documents/x/client6/; make builder
 mill --color false --watch x.compile
 [3/26] mill.scalalib.ZincWorkerModule.worker
 ^[[1A^[[2K^[[9999D[5/26] x.sources
 ^[[1A^[[2K^[[9999D[10/26] x.resources
 ^[[1A^[[2K^[[9999D[26/26] x.compile

**Comment by lihaoyi** [comment]
Not seeing this on my laptop?

**Comment by rayrobdod** [comment]
Those are ANSI escape codes. Not the change-color codes, more manipulate-the-cursor-location codes, but you wouldn't see them if and only if your terminal emulator interprets those codes.
