### ISSUE TITLE
Directly pull 'artifacts' from git

### ISSUE THREAD

**Issue by SRGOM** [lihaoyi/mill#469]

**Comment by SRGOM** [comment]
SBT has https://stackoverflow.com/questions/7550376/how-can-sbt-pull-dependency-artifact

Is it possible to do this in Mill? I think it belongs better in the courier project so I'm going to ask there too but figured I should ask here. If you do incorporate, it would be great if it were more in line with the libraryDependencies syntax with an easy list than the dependsOn syntax.

**Comment by lihaoyi** [comment]
Not possible

**Comment by nightscape** [comment]
"Not possible" as in "Not implemented", or as in "Violates some core principles and can't even be implemented without substantial effort"?

**Comment by lefou** [comment]
There is no functionality in mill that provides that feature out of the box. Of course, you can try to implemented a plugin/module that provides such feature.
