### ISSUE TITLE
Using unmanaged jars in a test suite

### ISSUE THREAD

**Issue by Ant01n3** [lihaoyi/mill#472]
Hello,

I may probably have missed something, but I cannot find a way to make my test suite use the same unmanaged jars than my module.

I put the same block in both the module and the test module :

```
def unmanagedClasspath =  T {
    if (!ammonite.ops.exists(millSourcePath / "lib")) Agg()
    else Agg.from(ammonite.ops.ls(millSourcePath / "lib").map(PathRef(_)))
}
```

but without success. I also tried to copy the lib directory inside the test/ directory but without any success either. Is there a specific way to do this ?

Thanks by advance

**Comment by lihaoyi** [comment]
the test module's millSourcePath is inside the test module folder. You need to say ` / up / "lib"`

**Comment by Ant01n3** [comment]
Thanks, it works. 

Needed to import first `ammonite.ops` for `up` to be known, but anyway it simplifies the use of `exists` and `ls`.

Thanks
