### ISSUE TITLE
Provide a mill wrapper to be included into repositories (`./mill`)

### ISSUE THREAD

**Issue by lefou** [lihaoyi/mill#476]
The wrapper should be:
* cross-platform
* small
* easy to inspect
* avoid containing bytecode (if needed, it could ad-hoc compile source code)

Use cases:
* Easy checkout and build without need to install mill
* Provide always the correct version of mill
* Easy to use mill in CI environments

**Comment by lihaoyi-databricks** [comment]
I'd be happy to just call it `./mill`. The leading `./` ensures there'll be no ambiguity with the PATH `mill` anyway.

I don't see any reason why the mill wrapper would need to be written in anything but Bash; it just needs to poke at some files and maybe download something.

**Comment by lihaoyi** [comment]
yeah bash works, and a mill.bat works too

**Comment by lefou** [comment]
I created project https://github.com/lefou/millw

But a Windows Batch version is still missing.
