### ISSUE TITLE
Running without the daemon

### ISSUE THREAD

**Issue by mgenereu** [lihaoyi/mill#495]
I'm on Windows 7 64-bit and mill.bat (0.3.5) fails to run:
```
C:\Users\mgenereu\Temp>mill.bat
Build repl needs to be run with the -i/--interactive flag
Failed to connect to server
```
The machine I'm on is running Symantec Endpoint Protection but most applications that communicate locally don't have issues.  Is there a way to run without the daemon? Is there something special about the connection to the daemon?

**Comment by lihaoyi** [comment]
questions go in gitter

**Comment by lefou** [comment]
When mill is started with `-i` / `--interactive` options, the daemon process is not used.
