### ISSUE TITLE
Contrib bottleneck for plugin development?

### ISSUE THREAD

**Issue by hejfelix** [lihaoyi/mill#500]
As I understand it, there's no external plugin architecture for mill. I also get why this makes sense, but it feels like it may be bottlenecking plugin development. 
Would it make sense to move to an incubator- like structure instead? I completely agree that many plugins should be defaults, but it would be good to have both options.

**Comment by lefou** [comment]
Mill plugins can be developed and published independently of mill repository. In fact, many are. Search for `mill-plugin`. Plugin authors are encouraged to get their plugins listed at http://www.lihaoyi.com/mill/page/contrib-modules.html#thirdparty-mill-plugins.

**Comment by lihaoyi** [comment]
questions go in gitter
