### ISSUE TITLE
Mill stuck for genIdea after I canceled it with Ctrl + C

### ISSUE THREAD

**Issue by hepin1989** [lihaoyi/mill#501]
After I canceled it with Ctrl + C and retry gen idea, it got stuck, only work after I clean it with `mill clean`.
The project is fastparse.

![image](https://user-images.githubusercontent.com/501740/49698605-0858bc00-fc01-11e8-98c7-a9b1ef77df36.png)

**Comment by lefou** [comment]
Can you reproduce it? Can you reproduce it with `-i` option?

**Comment by hepin1989** [comment]
@lefou may be the network issue, cannot reproduce it now, let me close it for now.
![image](https://user-images.githubusercontent.com/501740/49730050-25999300-fcb2-11e8-836e-98b75425a593.png)
