### ISSUE TITLE
Should L24 in docs Tasks.md be allSources()?

### ISSUE THREAD

**Issue by jkleckner** [lihaoyi/mill#538]
Should the line in `docs/4 - Tasks.md` that reads:
`  %("javac", sources().map(_.path.toString()), "-d", T.ctx().dest)(wd = T.ctx().dest)`
rather be:
`  %("javac", allSources().map(_.path.toString()), "-d", T.ctx().dest)(wd = T.ctx().dest)`
?

Or does `T.sources()` perform some magic?

**Comment by lefou** [comment]
Yes, you are right. `allSources` is correct.
