### ISSUE TITLE
Get error when add a comment to the build.sc file

### ISSUE THREAD

**Issue by wangchunsen** [lihaoyi/mill#545]
```Scala
// build.sc
import mill._ ,scalalib._

object foo extends ScalaModule {
  def scalaVersion = "2.12.8"

  def ivyDeps = Agg(
    ivy"com.lihaoyi::fastparse:2.1.0"
  )

  object test extends Tests {
    def ivyDeps = Agg(ivy"com.lihaoyi::utest:0.6.0")

    def testFrameworks = Seq("utest.runner.Framework")
  }
}


// mill mill.scalalib.GenIdea/idea
```  
This is my build file, when I added **the last line comment** to this file, then I got an error saying missing closing brace `}`. Just wondering anything I am doing wrong?
This is the full error msg that mill prints.

```
build.sc:70: Missing closing brace `}' assumed here
import mill._ ,scalalib._
^
Compilation Failed
```

**Comment by lihaoyi** [comment]
You're not doing anything wrong, this is just a bug: trailing comments trip up the code wrapper.

We should just fi it by adding some newlines before the trailing `}` in the wrapping code

**Comment by lihaoyi** [comment]
should be fixed by https://github.com/lihaoyi/mill/pull/660
