### ISSUE TITLE
Add `T.source` as an alternative to `T.sources` but for single files

### ISSUE THREAD

**Issue by lefou** [lihaoyi/mill#546]
Using `T.sources` in case where only a single file is expected, leads to unnecessary error sources.

**Comment by lefou** [comment]
I'm asking myself, if the already present `T.input[PathRef]` is enough.

According to documentation and my personal experience, `T.input[Seq[PathRef]]` and `T.sources` should behave identical, except the more specialized type.

**Comment by lefou** [comment]
So, instead of a new `def myFile = T.source(theFile)` we might just write `def myFile = T.input(PathRef(theFile))`

**Comment by lihaoyi** [comment]
https://github.com/lihaoyi/mill/pull/749
