### ISSUE TITLE
Add proper import statements to "Contrib Modules" documentation page

### ISSUE THREAD

**Issue by lefou** [lihaoyi/mill#547]
Currently, they are missing and the user has no guide how to use the plugins.

Missing imports in:
* BuildInfo
* ScalaPB (partially)
* TestNG

Possibly incorrect imports (hard-coded version differs from mill version):
* Twirl
* Play Framework

**Comment by jeantil** [comment]
Is there a way to have the current version inserted in the documentation automatically ?

**Comment by lefou** [comment]
> Is there a way to have the current version inserted in the documentation automatically ?

Currently not, unfortunately.
