### ISSUE TITLE
Add nice prettyprints/toString for the Build REPL 

### ISSUE THREAD

**Issue by lihaoyi** [lihaoyi/mill#56]
Currently, the toStrings you get inspecting tasks/modules in the REPL is pretty bare:

```scala
lihaoyi mill$ scalaplugin/target/mill --repl
Loading...
@ build
res0: build.type = build

@ build.Core
res1: Core.type = ammonite.predef.$up.build$Core$@33ce764b

@ build.Core.compile
res2: T[scalaplugin.CompilationResult] = mill.define.Persistent@ddd029e
```

While you can poke around with autocomplete or `typeOf(build).members`, it would be nice to hook into Ammonite's pretty-printer and use it to show nicer output at the REPL:

```scala
lihaoyi mill$ scalaplugin/target/mill --repl
Loading...
@ build
res0: build.type = build
Children:
- build.Core
- build.ScalaPlugin
- build.bridges

@ build.Core
res1: Core.type = build.Core
Children:
- build.Core.assembly
- build.Core.basePath
- build.Core.classpath
- build.Core.compile
- build.Core.compileDepClasspath
- build.Core.console
...

@ build.Core.compile
res2: T[scalaplugin.CompilationResult] = build.Core.compile
Inputs:
- build.Core.scalaVersion
- build.Core.allSources
- build.Core.compileDepClasspath
- build.Core.scalaCompilerClasspath
- build.Core.compilerBridgeClasspath
- build.Core.scalacOptions
- build.Core.scalacPluginClasspath
- build.Core.javacOptions
- build.Core.upstreamCompileOutput
```

This can be done by hooking into the Ammonite REPL pretty-printer:

```scala
repl.pprinter() = repl.pprinter().copy(additionalHandlers = ...)
```

We can make use of the `Discovered` mirror within the `additionalHandlers`, which should contain the information needed for labelling all the `Task`s

It might be harder to hook into `toString` output, since we can't make use of the `Discovered` mirror within `toString`, but maybe there's still something we can do there

**Comment by lihaoyi** [comment]
Closed by 3d0b4b2591b6ea812bd15ab4b82ab004ed9d2138

<img width="829" alt="screenshot 2018-01-03 21 00 31" src="https://user-images.githubusercontent.com/934140/34550871-373108be-f0c9-11e7-9085-7ce10e35776d.png">

**Comment by rockjam** [comment]
@lihaoyi is this line needed? https://github.com/lihaoyi/mill/commit/3d0b4b2591b6ea812bd15ab4b82ab004ed9d2138#diff-6f6f3501afe6f63edc6817acdcbc32bfR79

**Comment by lihaoyi** [comment]
@rockjam probably not, just leftover dirt from my messing around
