### ISSUE TITLE
Supporting release to Nexus OSS, i.e. without staging

### ISSUE THREAD

**Issue by rand00** [lihaoyi/mill#576]
The existing version of mill (0.3.6) is written to primarily support snapshot- and staged releases. We have our own Nexus OSS running, and as it's only the Pro version that supports staging, we've had to redefine the publishing logic in our `build.sc`

https://gist.github.com/rand00/658b675ca72bf41805e9fc6affe98ca3#file-build-scala-L53
_Edit:_ TL;DR; the redefined `publishRelease` is almost equal to `publishSnapshot`, except for the uri used

It seems to me like the existing `publishRelease` method on `SonatypePublisher` should be renamed to `publishStagedRelease`, as the existing `release` and `stagingProfile` parameters are specific to staged releases. But this would of course be a breaking change. The `publishRelease` method could become the way to do non-staged releases.

Also, the `uri` parameter to `SonatypePublisher` is not the same for staged and non-staged releases, e.g.:
* staging URI: "https://server.org/service/local"
* non-staging URI: "https://server.org/repository/repo-name/" 

So this uri is also semantically bound to which publish-method that is called. This could be relevant for users that want to publish to several repositories

**Comment by lefou** [comment]
Fixed by #739
