### ISSUE TITLE
Watch & re-run functionality in the REPL

### ISSUE THREAD

**Issue by lihaoyi** [lihaoyi/mill#58]
You currently can use Ammonite's `--watch` flag to watch & re-run targets from the Bash shell. When used to run the REPL, `--watch` only serves to re-start the REPL if you exited it after making changes.

We should provide a `watch(Core.compile)` function that can be used to watch & re-run a one ([or more](https://github.com/lihaoyi/mill/issues/57)) targets from Build REPL

**Comment by duncanmak** [comment]
@lihaoyi Now that @rockjam has implemented #57, should I follow suit and generate a watch function in the REPL context?

I'll have to find out how Ammonite's `--watch` flag is wired up, and invoke that directly.

**Comment by lihaoyi** [comment]
@duncanmak yeah that seems reasonable, feel free to assign this to yourself if you work on it

**Comment by lihaoyi** [comment]
This is probably moot since now the client-server model makes bash-execution fast. There is much less need to spend time in the REPL other than poking around the build: most normal running/watching will be from the terminal
