### ISSUE TITLE
Clarify what artifact id will be used to publish

### ISSUE THREAD

**Issue by kag0** [lihaoyi/mill#584]
There is currently no field in `PomSettings` for the maven artifact id. I didn't see anywhere in the documentation that specified how the artifact id would be resolved. 
Is it the name of the module object? The `artifactId` field on `JavaModule`?

This is a setting that users might want in order to customize how their artifact is published.

**Comment by lihaoyi** [comment]
Not sure what you're asking, but questions can be asked on the gitter channel

**Comment by kag0** [comment]
I should have clarified, I meant to request the documentation be updated to include this information.
I'll go ask on gitter and try with a PR once I have the answer, thanks.
