### ISSUE TITLE
For Dotty, download the binary version of the compiler bridge instead of compiling it from sources

### ISSUE THREAD

**Issue by smarter** [lihaoyi/mill#591]
Starting with Dotty 0.13.0-RC1, the bridge is a Java-only project (https://github.com/lampepfl/dotty/tree/master/sbt-bridge/src/xsbt) and binary artifacts are published on Maven: https://repo1.maven.org/maven2/ch/epfl/lamp/dotty-sbt-bridge/0.13.0-RC1/. This means you can avoid all the complications caused by having to fetch it sources, compiling these sources, caching the result, etc. In particular, it means https://github.com/lihaoyi/mill/issues/389 ceases to be a problem.

The relevant code in mill is in https://github.com/lihaoyi/mill/blob/master/scalalib/worker/src/ZincWorkerImpl.scala

**Comment by lefou** [comment]
What exactly is the issue here? Doesn't commit 981c4e1d6919e3a4ceea6a4c63335d7b69d9e8aa fix the Java-only compilation for the compiler bridge?

**Comment by lefou** [comment]
For reference: https://github.com/lihaoyi/mill/pull/569

**Comment by smarter** [comment]
This is a request for enhancement not a bug :). The current solution works fine, but as explained above, using a pre-built binary version of the bridge avoids a lot of complications (and is faster for the initial compilation too).
