### ISSUE TITLE
Cannot refer to `T.ctx` when delegating to another command

### ISSUE THREAD

**Issue by andres-pipicello-olx** [lihaoyi/mill#596]
When defining a `T.command`, is not possible to refer to `T.ctx()` if that value is passed as an argument to another command invocation.

This works
```scala
  def delegatee(string: String) = T.command{???}

  def works() = T.command {
    println(T.ctx().dest.toString())
    delegatee("dummy")()
  }
```
but this does not
```scala
  def delegatee(string: String) = T.command{???}

  def doesNotWorks() = T.command {
    delegatee(T.ctx().dest.toString())()
  }
```

See https://github.com/andres-pipicello-olx/mill-project-test for complete example

**Comment by lihaoyi** [comment]
Yeah this is an unfortunate consequence of how commands/tasks are set up. As a workaround, you can do something like:
```scala
  def delegatee0(string: String) = {???}
  def delegatee(string: String) = T.command{delegatee0(string)}

  def doesNotWorks() = T.command {
    delegatee0(T.ctx().dest.toString())
  }
```

This is an inherent consequence of the fact that `T.command`s are basically `(T1, T2, ..., Tn) => Command[V]` rather than `Command[(T1, T2, ..., Tn) => V]`. Not pretty, but I don't see any way around it for now

**Comment by lefou** [comment]
Looks like we should open a new FAQ-like section in the docs: commonly seen error message

**Comment by andres-pipicello-olx** [comment]
The problem is the impossibility of doing something like overriding the behavior of a command just by calling using `super.command` with some additional parameters that come from T.ctx.

My specific use case is to add the option for generating JUnit reports to the Scalatest framework, and I want it to be generated in the `dest`directory.

```scala
override def test(args: String*) = T.command {
  super.test(Seq("-u", (T.ctx().dest / "junit").toString) ++ args:_*)
}

```
