### ISSUE TITLE
Multiple ivy dependencies act inconsistent when ScalafmtModule is applied to ScalaJSModule

### ISSUE THREAD

**Issue by mgenereu** [lihaoyi/mill#597]
May be a duplicate of #442 but multiple ivy dependencies can't find resources in the maven repository.  Removing the ScalafmtModule resolves the issue.

**Comment by lefou** [comment]
Is this still an issue? #442, which was marked as a possible duplicate, is already closed. Could you please provide a `build.sc` to reproduce the issue?

**Comment by mgenereu** [comment]
I'll look into it now.

**Comment by mgenereu** [comment]
Confirmed closed.  ScalaJSModule is now working correctly when ScalafmtModule is added. Thank you!
