### ISSUE TITLE
ScalaJSModule#Tests fails to resolve test framework when moduleKind is set

### ISSUE THREAD

**Issue by Baccata** [lihaoyi/mill#601]
Found in mill 0.3.6 

### Minimal example to reproduce 

```scala
import mill._
import mill.scalalib._
import mill.scalajslib._
import ammonite.ops._

object pipo extends ScalaJSModule {

  def scalaVersion = "2.12.8"
  def scalaJSVersion ="0.6.26"

  object test extends Tests {
    override def ivyDeps = Agg(ivy"com.lihaoyi::utest::0.6.6")
    override def testFrameworks = Seq("utest.runner.MillFramework")
    // Commenting out the following line results in no-crash. 
    override def moduleKind = T(mill.scalajslib.api.ModuleKind.CommonJSModule)
  }
}
```

### Error message : 

```
oliviermelois@otana:/tmp/pipo$ mill pipo.test
Compiling /private/tmp/pipo/build.sc
[74/75] pipo.test.fastOptTest 
Linker: Compute reachability: 371294 us
Linker: Assemble LinkedClasses: 1376240 us
Basic Linking: 1964107 us
Emitter: Class tree cache stats: reused: 1054 -- invalidated: 1062
Emitter: Method tree cache stats: resued: 0 -- invalidated: 10560
Emitter (write output): 904164 us
[75/75] pipo.test.test 
Starting process: node
1 targets failed
pipo.test.test java.lang.RuntimeException: Failed to get framework
    mill.scalajslib.worker.ScalaJSWorkerImpl.$anonfun$getFramework$3(ScalaJSWorkerImpl.scala:75)
    scala.Option.getOrElse(Option.scala:138)
    mill.scalajslib.worker.ScalaJSWorkerImpl.getFramework(ScalaJSWorkerImpl.scala:75)
    mill.scalajslib.ScalaJSWorker.getFramework(ScalaJSWorkerApi.scala:63)
    mill.scalajslib.TestScalaJSModule.$anonfun$test$1(ScalaJSModule.scala:179)
    mill.define.ApplyerGenerated.$anonfun$zipMap$6(Applicative
```

**Comment by Baccata** [comment]
Relevant convo from the sjs gitter : https://gitter.im/scala-js/scala-js?at=5cd01bc5e416b845193c9444

**Comment by javaduke** [comment]
I'm running into the same issue when building my project, is there any fix for it?

**Comment by gzm0** [comment]
Note that this should be a problem on Scala.js 0.6 only. The issue seems to be that `ScalaJSWorkerImpl.scala` does not set [`moduleSettings`][1] on the `TestAdapter.Config`:

https://github.com/lihaoyi/mill/blob/158d117d7e92a4705fdd783952032bdc14bf92e8/scalajslib/worker/0.6/src/ScalaJSWorkerImpl.scala#L65

Therefore, the `TestAdapter` is unable to load the framework.

[1]: http://www.scala-js.org/api/scalajs-sbt-test-adapter/0.6.28/index.html#org.scalajs.testadapter.TestAdapter$$Config@withModuleSettings(moduleKind:org.scalajs.core.tools.linker.ModuleKind,moduleIdentifier:Option[String]):org.scalajs.testadapter.TestAdapter.Config

**Comment by lefou** [comment]
Fixed in #706

**Comment by tballard** [comment]
Apparent same issue with mill 0.6.3, scala.js 1.0.0:
client.test.test java.lang.RuntimeException: Failed to get framework
mill.scalajslib.worker.ScalaJSWorkerImpl.$anonfun$getFramework$3(ScalaJSWorkerImpl.scala:99)
scala.Option.getOrElse(Option.scala:189)

**Comment by lefou** [comment]
@tballard "Failed to get framework" is an indicator that the test framework class was not found. Can you please check that:
* there are no typos in the framework class
* the framework lib is on the classpath
* the correct Scala.js dependency of the framework is used (not the Scala one): e.g. `ivy"g::a::v"`
