### ISSUE TITLE
Make it easier to create "optional" dependencies

### ISSUE THREAD

**Issue by lefou** [lihaoyi/mill#603]
If you need to set the `optional` flag (Maven semantics) to a dependency, you can not do it with the `ivy` string context or it's returned `Dep` instance. Instead you have to manipulate the enclosed coursier dependency object, which is cumbersome.

I suggest adding a `optional` def to `mill.scalalib.Dep`.

Example:

```scala
ivy"org.slf4j:slf4j-api:1.7.25".optional(true)
```

**Comment by lihaoyi** [comment]
sounds good

**Comment by lefou** [comment]
Currently, published ignores the optional-flag.
