### ISSUE TITLE
Unable to issue mill -i clean for upickle, file reported as used by another process

### ISSUE THREAD

**Issue by OndrejSpanel** [lihaoyi/mill#606]
I have upickle cloned on my disk, bash shell running in the upickle directory. Whenever I issue `mill -i clean`, I get following error:

> 1 targets failed
>
>clean java.nio.file.FileSystemException: W:\OpenSource\upickle\out\clean\log: The process cannot access the file because it is being used by another process.

Process Explorer search did not find any other process using the file and I able to delete the file manually without any issue. Even after removing it, on the next run the fresh "clean/log" file is created and the same error is reported again.

Running mill 0.3.6 installed using scoop on Windows 10 x64, Java 8.

**Comment by lefou** [comment]
Could you check if #731 fixed your issue?
