### ISSUE TITLE
Changes in upickle macros not reflected unless out/implicits is cleared

### ISSUE THREAD

**Issue by OndrejSpanel** [lihaoyi/mill#607]
I ran a test by using the following command line: 
`mill -i upickle.js[2.12.7].test upickle.example.ExampleTests.defaults.writing`

The test is passed as expected.

I break the defaults handling code by changing:

- in `getArgSyms`: `flattened.map(_ => false)` instead of `flattened.map(_.asTerm.isParamWithDefault)`

- in `deriveDefaults`: `if (true) q"null"` instead of `if (!hasDefault) q"null"`

I run the test again by:

`mill -i upickle.js[2.12.7].test upickle.example.ExampleTests.defaults.writing`

The test is still passed, which is wrong. When I delete the "upickle/out" or "upickle/out/implicits" directory and run the same command again, the test is failed as is should.

Running mill 0.3.6 installed using scoop on Windows 10 x64, Java 8.

**Comment by lihaoyi** [comment]
This is expected and is a property of Zinc/Scalac; not much Mill can do about it
