### ISSUE TITLE
Only one `Task` in a group should be allowed to use the `T.ctx().dest` directory

### ISSUE THREAD

**Issue by lihaoyi** [lihaoyi/mill#62]
`Task`s are grouped together under their downstream `Target` before running, and every `Task` in that group has the same `T.ctx().dest` which is defined by the path to the downstream `Target`. Currently there is nothing stopping multiple `Task`s from reading/writing from `dest`, which could allow for unintended interference between them.

We should fail with an error if more than one `Task` attempts to use the `dest` dir, for any purpose.  How to provide a nice error message, given that `Task`s don't need to have names, is a bit of an open question: maybe the stack trace of the points which use `.dest` are good enough?

**Comment by duncanmak** [comment]
@hepin1989 @lihaoyi is this still open?

**Comment by lihaoyi** [comment]
@duncanmak yeah this is still open
