### ISSUE TITLE
Support Class-Path in jar manifest

### ISSUE THREAD

**Issue by lilyevsky** [lihaoyi/mill#624]
Currently the jar task does not support the Class-Path attribute.

This attribute is one of the general main jar attributes, see https://docs.oracle.com/javase/8/docs/technotes/guides/jar/jar.html#Main_Attributes .

The Class-Path is very important for standalone apps that are deployed as a collection of jar files, the main jar and dependent libraries (not as uber-jar).

**Comment by lefou** [comment]
You can overwrite the `def manifest: T[JarManifest]` target and append any manifest entry you want, including `Class-Path`.
