### ISSUE TITLE
Publish snapshots to maven repository with unique version

### ISSUE THREAD

**Issue by lilyevsky** [lihaoyi/mill#625]
Currently the publish task always uploads snapshot artifacts to Nexus using the exact version name,
for example, 'myartifact-1.2.5-SNAPSHOT.jar', so it basically overrides the previously uploaded snapshot.
There is no option to do the unique version, when the 'SNAPSHOT' word is replaced by some unique string, just like it is done in maven.

**Comment by lefou** [comment]
You can and you should return the version you want via the `publishVersion` target. If you want to use a timestamp, as Maven does in case of "deploy", you can simply calculate it in a single target and refer to that value in all other `publishVersion` targets.
Another often seen pattern is to use a git tag and potentially some hash in case there is no exact tag. Some do event include some dirty flag and another hash in case the repo version has local modifications. Mill does it this way.

But a treatment like Maven does is inconsistent and not reproducible. I guess, mill will not implement that replacement unless someone comes up with a pull requst and good arguments.

**Comment by lilyevsky** [comment]
Hi @lefou ,
I feel like I need to reopen this issue. I didn't have a chance to play with mill for a long time, now I am back.
For the last year mill made a lot of progress, I really like it and I want to start using it for real stuff.
I believe that for its success it is very important to make sure it can support team development where other projects use tolls like maven, gradle, etc. Otherwise transition would be impossible.
I don't quite agree with you saying that "Maven does is inconsistent and not reproducible". In fact, maven uses this approach for many years now, this is how snapshots are stored in repositories like Nexus, and as of Maven 3 only unique snapshot versions are supported.
Snapshots are critical for team collaboration during development. 

I actually tried your suggestion of redefining publishVersion. There is a problem with it: it changes not only the name of the artifact file, but also the folder name. This is not how snapshot must be stored. See https://blog.packagecloud.io/eng/2017/03/09/how-does-a-maven-repository-work/#unique-snapshots .

For example, if version is 1.2-SNAPSHOT, and unique version is 1.2-12345.6789-1 (this is just dummy example), then it should be stored as
..../myartifact-1.2-SNAPSHOT/myartifact-1.2-12345.6789-1.jar
not as 
..../myartifact-1.2-12345.6789-1/myartifact-1.2-12345.6789-1.jar
like it happens when I redefine publishVersion.

Maybe you can suggest another workaround how to achieve this?

Thanks in advance.

**Comment by lefou** [comment]
Storing different snapshot versions in the same `SNAPSHOT` path is currently not supported by mill, I think. I guess a pull request to change that should not be very hard, but I have no clear idea what change is required to properly support such magic SNAPSHOT versions consistently in mill and in ivy repos. If you provide some documentation outlining how those magic SNAPSHOTs are handled in ivy, I'm open for acccepting such change though.

Also, I stand by my claim that magic SNAPSHOTs are  is not reproducible (in Maven), as you can not reproduce a release of the exact binary versions at a later time on the same or another machine with maven. You will always end up with different timestamps. I'm also not aware of any (hidden) switch to force the timestamp to a given point back in time.

**Comment by lefou** [comment]
> I believe that for its success it is very important to make sure it can support team development where other projects use tools like maven, gradle, etc. Otherwise transition would be impossible.

I don't see where mill in it's current version inhibits polyglot/diverse environments.

**Comment by lilyevsky** [comment]
@lefou I don't know about ivy repos, maybe snapshots are not relevant there. I only care about maven repositories, where I found them extremely useful.
You are confusing two different aspects of publishing. I now understand what you mean by "not reproducible". However, for the snapshot we don't care about being reproducible. Snapshot is not release, it has different purpose.  Snapshots are used during active development of a component which is utilized by another project under development. Snapshots are never published in official repositories such as Central repo. They are only published in local repos like Nexus inside organization.
In Nexus the snapshots are published in a separate 'snapshots' repository with a special retention policy - old snapshots are deleted automatically.
Here is the typical use scenario. Let say I am working on a library project and my friend is working on another project that uses my library. I make a change and publish the snapshot, now my friend can just recompile his stuff. That's it.
Without snapshots, I would need to change the version of my project, publish it, tell my friend the new version number. After few days of development like that we will have tens of useless artifacts that must be manually deleted. On top of this headache, I cannot delete artifacts myself - have to ask Nexus administrator. Not very productive.
Again, you should not worry about reproducible artifacts here. After my artifact is ready, I obviously change its version to a release and when I publish, it automatically goes to 'releases' repository; this is of course reproducible.

**Comment by lilyevsky** [comment]
@lefou 
Actually, it looks like it may be satisfactory the way it is now.

When publishing in Nexus, it indeed has exact same version as the previous upload, but it overrides it (which Nexus allows in snapshot repository).
On the other gradle project it will properly refresh if I specify --refresh-dependencies flag.
In maven project, I assume, it will do the same thing, but currently we don't use maven for builds, so I did not test this.

Question to you: if my other project is also mill, how can I tell it to refresh dependencies?
Obviously I can clean the coursier cache, but hopefully there is a better way?
