### ISSUE TITLE
Jvm.resolveDependencies not resolving servlet jar properly?

### ISSUE THREAD

**Issue by lihaoyi** [lihaoyi/mill#629]
The following `ivyDeps` doesn't seem to include `org.eclipse.jetty.orbit:javax.servlet:3.0.0.v201112011016`:

```scala
lihaoyi mill$ cat scratch/build.sc
import mill.Agg
import mill.scalalib._

object core extends ScalaModule{
  def scalaVersion = "2.12.8"
  def ivyDeps = Agg(
    ivy"org.eclipse.jetty:jetty-websocket:8.1.16.v20140903",
    ivy"org.eclipse.jetty:jetty-server:8.1.16.v20140903"
  )
}

lihaoyi mill$ mill -i dev.run scratch show core.runClasspath
Compiling (synthetic)/ammonite/predef/interpBridge.sc
[587/587] dev.run
Mill version changed (0.4.1-4-2b68a7-DIRTY1b11a4c6 -> 0.4.1-4-2b68a7-DIRTY57b172ca), re-starting server
1 targets failed
dev.run java.lang.Exception: Interactive Subprocess Failed (exit code 101)
    mill.modules.Jvm$.runSubprocess(Jvm.scala:87)
    mill.modules.Jvm$.baseInteractiveSubprocess(Jvm.scala:74)
    ammonite.$file.build$dev$.$anonfun$run$1(build.sc:559)
    mill.define.ApplyerGenerated.$anonfun$zipMap$1(ApplicativeGenerated.scala:5)
    mill.define.Task$MappedDest.evaluate(Task.scala:337)
lihaoyi mill$ mill -i dev.run scratch show core.runClasspath
[587/587] dev.run
Compiling (synthetic)/ammonite/predef/interpBridge.sc
Compiling /Users/lihaoyi/Github/mill/scratch/build.sc
[1/1] show
[29/29] core.runClasspath
[
    "ref:c984eca8:/Users/lihaoyi/Github/mill/scratch/core/resources",
    "ref:c984eca8:/Users/lihaoyi/Github/mill/scratch/out/core/compile/dest/classes",
    "qref:e747c96d:/Users/lihaoyi/.coursier/cache/v1/https/repo1.maven.org/maven2/org/eclipse/jetty/jetty-continuation/8.1.16.v20140903/jetty-continuation-8.1.16.v20140903.jar",
    "qref:00a3f553:/Users/lihaoyi/.coursier/cache/v1/https/repo1.maven.org/maven2/org/eclipse/jetty/jetty-io/8.1.16.v20140903/jetty-io-8.1.16.v20140903.jar",
    "qref:a1ce2c81:/Users/lihaoyi/.coursier/cache/v1/https/repo1.maven.org/maven2/org/eclipse/jetty/jetty-websocket/8.1.16.v20140903/jetty-websocket-8.1.16.v20140903.jar",
    "qref:9c193a25:/Users/lihaoyi/.coursier/cache/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.8/scala-library-2.12.8.jar",
    "qref:255c632e:/Users/lihaoyi/.coursier/cache/v1/https/repo1.maven.org/maven2/org/eclipse/jetty/jetty-http/8.1.16.v20140903/jetty-http-8.1.16.v20140903.jar",
    "qref:75e0bf92:/Users/lihaoyi/.coursier/cache/v1/https/repo1.maven.org/maven2/org/eclipse/jetty/jetty-util/8.1.16.v20140903/jetty-util-8.1.16.v20140903.jar",
    "qref:3977f444:/Users/lihaoyi/.coursier/cache/v1/https/repo1.maven.org/maven2/org/eclipse/jetty/jetty-server/8.1.16.v20140903/jetty-server-8.1.16.v20140903.jar"
]
```

On the other hand, plugging the same deps into the coursier online demo (https://get-coursier.io/demo/#resolution) seems to include it:

<img width="1193" alt="Screenshot 2019-06-13 22 00 40" src="https://user-images.githubusercontent.com/934140/59463617-b6e6ef00-8e26-11e9-95c2-05cd0b0bc256.png">

This is blocking migration of Scalatags to Mill, as Scalatags requires Scala.js's PhantomJsEnv which requires jetty-server which requires `javax.servlet.http.HttpServletResponse` from `org.eclipse.jetty.orbit:javax.servlet:3.0.0.v201112011016`

@alexarchambault any idea what's going on here? Not sure if it's a coursier bug or if we're misconfiguring it somewhere

**Comment by lihaoyi** [comment]
@alexarchambault here's a smaller repro, using only Ammonite:

```scala
@ import $ivy.`org.eclipse.jetty.orbit:javax.servlet:3.0.0.v201112011016`
import $ivy.$

@ classOf[javax.servlet.http.HttpServletResponse]
cmd1.sc:1: type HttpServletResponse is not a member of package javax.servlet.http
val res1 = classOf[javax.servlet.http.HttpServletResponse]
                                      ^
Compilation Failed
```

**Comment by alexarchambault** [comment]
@lihaoyi It seems that originates from the jar of javax.servlet to have a weird packaging tag (look for `packaging` in [its POM](https://repo1.maven.org/maven2/org/eclipse/jetty/orbit/javax.servlet/3.0.0.v201112011016/javax.servlet-3.0.0.v201112011016.pom)).

I'm going to change the default artifact types in coursier, so that that one is included too (going to include the [same](https://github.com/sbt/sbt/blob/47cd001eea8ef42b7c1db9ffdf48bec16b8f733b/main/src/main/scala/sbt/Defaults.scala#L227) [types](https://github.com/sbt/librarymanagement/blob/bb2c73e183fa52e2fb4b9ae7aca55799f3ff6624/ivy/src/main/scala/sbt/internal/librarymanagement/CustomPomParser.scala#L79) as sbt). In the mean time, you can pass explicit artifact types to the `coursier.Resolution.artifacts` method called [around here](https://github.com/lihaoyi/mill/blob/d12a0d762193d83f83c837eb4affad389744a6cd/main/src/modules/Jvm.scala#L448). Something like 
```scala
import coursier.Type
resolution.artifacts(artifactTypes = Set(Type.jar, Type.testJar, Type.bundle, Type("orbit")))
```
should work.

**Comment by lihaoyi** [comment]
sounds good, will do that, thanks!

**Comment by lihaoyi** [comment]
sounds good, will give it a shot and close this if it works
