### ISSUE TITLE
TestRunner doesn't take forkArgs into account

### ISSUE THREAD

**Issue by shishkin** [lihaoyi/mill#631]
I'm trying mill and utest with GraalVM Truffle framework, which requires a JVM argument `-XX:-UseJVMCIClassLoader` in testing. Despite me configuring `def forkArgs = Seq("-XX:-UseJVMCIClassLoader")` in the test module, the argument has no effect. ScalaTest has the same issue, although in SBT both work just fine. Also, when I create a main class in my test module to run `utest.TestRunner.run(MyTest.tests)` standalone, all works just fine.

I see that `JavaModule.test` passes `forkArgs` to the `TestRunner.main` in https://github.com/lihaoyi/mill/blob/master/scalalib/src/JavaModule.scala#L572. Not sure, if `TestRunner` handles JVM args correctly in https://github.com/lihaoyi/mill/blob/master/scalalib/src/TestRunner.scala#L72.

Any ideas how to troubleshoot this further?

**Comment by lihaoyi** [comment]
Can you try asking in the gitter channel?
