### ISSUE TITLE
Reached max process limit: 0 on Windows10

### ISSUE THREAD

**Issue by fujohnwang** [lihaoyi/mill#642]
Please don't open issues for questions, but ask in our gitter channel at https://gitter.im/lihaoyi/mill
![27411561512997_ pic_hd](https://user-images.githubusercontent.com/451506/60144779-4f517c00-97f6-11e9-93b6-5402ae206834.jpg)

**Comment by crimzie** [comment]
I'm seeing the same bug on Os X
```
Exception in thread "main" java.lang.Exception: Reached max process limit: 0
	at mill.main.client.MillClientMain.main0(MillClientMain.java:156)
	at mill.main.client.MillClientMain.main(MillClientMain.java:82)
```
when I run any command. this happens with only one project/working directory and cleaning caches or shutting down mill server doesn't help.

**Comment by lemastero** [comment]
For me removing `out` directory solved the issue.

**Comment by lefou** [comment]
This happens, when there are already 5 busy running mill server instances. Removing the `out` directory triggers a shutdown of all of these processes, as these are watching their management directories (`out/mill-worker-*`).
