### ISSUE TITLE
New Mill wrapper script is not Powershell/CMD compatible

### ISSUE THREAD

**Issue by nightscape** [lihaoyi/mill#654]
Hi all,

the recently released wrapper script does not seem to be compatible with Powershell or CMD on Windows.
I have written a Mill installer for Scoop on Windows and this currently breaks because it downloads the file `0.5.0` on the Github release page which is the wrapper and not the assembly anymore.
Do you plan to leave the naming like that?
If so, I would change the Scoop installer to download the `0.5.0-assembly` file.

**Comment by lihaoyi-databricks** [comment]
@nightscape I think swap over to the `x.y.z-assembly` file for now. We'll maintain the convention going forward that the file named `x.y.z` is the thing to install on unix systems (which takes precedence), and the `x.y.z-assembly` file is the "raw" executable jar

**Comment by nightscape** [comment]
Ok, done so here: https://github.com/ScoopInstaller/Main/pull/234/files
