### ISSUE TITLE
Have Mill output timing info like SBT

### ISSUE THREAD

**Issue by nhooey** [lihaoyi/mill#656]
It would be great if Mill output the amount of time it took to complete something, so users would know truly how fast it is:

**SBT timing output:**
```
[success] Total time: 0 s, completed Jul. 10, 2019, 8:32:09 p.m.
```

**Comment by lihaoyi** [comment]
This is present in the out/mill-profile.json

**Comment by nhooey** [comment]
Would you consider having this displayed in the build output so you can always see it when using `mill --watch thing.run`?

**Comment by lihaoyi** [comment]
We don’t currently print things on successful runs; maybe under a flag like `--timing`?

**Comment by nhooey** [comment]
Yeah that would be great. Being able to provide a list of tasks to print timings for would help keep down the clutter.

Something like `--timing core.compile`.

My motivation for asking for this is to help advertise how fast Mill is. For these timings to start showing up all over the web in build output that people paste in questions.
