### ISSUE TITLE
Scalafmt module is broken

### ISSUE THREAD

**Issue by markehammons** [lihaoyi/mill#676]
When attempting to reformat my projects using `project.reformat` or `mill.scalalib.scalafmt.ScalafmtModule/reformat _.sources`, I will get the following target failure:

```
mill.scalalib.scalafmt.ScalafmtModule.reformatAll java.nio.file.FileSystemNotFoundException
    com.sun.nio.zipfs.ZipFileSystemProvider.getFileSystem(ZipFileSystemProvider.java:171)
    com.sun.nio.zipfs.ZipFileSystemProvider.getPath(ZipFileSystemProvider.java:157)
    java.nio.file.Paths.get(Paths.java:143)
    mill.scalalib.scalafmt.ScalafmtWorker.reformatAction(ScalafmtWorker.scala:59)
    mill.scalalib.scalafmt.ScalafmtWorker.reformat(ScalafmtWorker.scala:32)
    mill.scalalib.scalafmt.ScalafmtModule$.$anonfun$reformatAll$2(ScalafmtModule.scala:32)
    scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
```

**Comment by markehammons** [comment]
I have a fix for the stack trace, but the default scalafmt file can't be reached. java's NIO seems to be having trouble reading the data embedded inside the mill launcher/package

**Comment by jodersky** [comment]
Looks like the issue only appears when attempting to extract a bundles default config for scalafmt. A workaround for this is to create the config file excplicity. E.g. `touch .scalafmt.conf`

**Comment by markehammons** [comment]
@jodersky this is what my referenced fix does.

**Comment by mgenereu** [comment]
I can confirm this bug. The `touch` method worked. This used to work.
