### ISSUE TITLE
mill.scalalib.Dependency/updates is reading stale deps

### ISSUE THREAD

**Issue by nafg** [lihaoyi/mill#689]
I ran `mill mill.scalalib.Dependency/updates` and updated my ivyDeps accordingly, then ran it again, and it still reported the updates as if my build.sc still had the same version as initially

However if I did a compile in between then the subsequent updates check would see the changes I made to the dependencies.

**Comment by guilgaly** [comment]
There was apparently a similar issue with the GenIdea task : #352. I don't know if the cause is the same, but it may be.

**Comment by lefou** [comment]
@nafg, can you please test with #702 and report, it this solves the issue?

**Comment by ajrnz** [comment]
Hey thanks, this was bugging me as well (`rm -rf out`...). I can confirm that #702 fixes it.
