### ISSUE TITLE
Can not run mill in fish

### ISSUE THREAD

**Issue by suda-morris** [lihaoyi/mill#692]
OS: Manjaro
Shell: Fish
Way install mill: sudo pacman -S mill
Issue:
When run `mill version`, I got :
```bash
Failed to execute process '/usr/bin/mill'. Reason:
exec: Exec format error
The file '/usr/bin/mill' is marked as an executable but could not be run by the operating system.
```
The error won't occur after switch to bash, so how to make mill also work in other bash (e.g. fish)?

**Comment by lihaoyi** [comment]
Seems something is wrong with the pacman package; the manual installation instructions include prepending the correct shebang line to the executable
