### ISSUE TITLE
Mill not running Java Junit tests

### ISSUE THREAD

**Issue by eyalroth** [lihaoyi/mill#698]
## Description

Mill seem to not run Java JUnit tests.

## Project Setup

```
/
  build.sc
  core/
    src/
      HelloWorld.java
    test/
      src/
        HelloWorldTest.java
```
`build.sc` (pretty much as in the documentation):
```scala
import mill._, scalalib._

trait JUnitTests extends TestModule {
  def testFrameworks = Seq("com.novocode.junit.JUnitFramework")
  def ivyDeps = Agg(ivy"com.novocode:junit-interface:0.11")
}

object core extends JavaModule {
  object test extends Tests with JUnitTests
}
```

HelloWorld.Java:
```java
public class HelloWorld {
    public void print(String message) {
        System.out.println(message);
    }
}
```
HelloWorldTest.java:
```java
import org.junit.Test;

class HelloWorldTest {
    @Test
    public void print() throws Exception {
        throw new Exception();
    }
}
```

## Execution

```
$ mill -i core.test
[23/42] core.compile
[info] Compiling 1 Java source to /mnt/c/Users/eyal/repos/mill-java/out/core/compile/dest/classes ...
[info] Done compiling.
[36/42] core.test.compile
[info] Compiling 1 Java source to /mnt/c/Users/eyal/repos/mill-java/out/core/test/compile/dest/classes ...
[info] Done compiling.
[42/42] core.test.test
$
```

## Environment
**Mill**: 0.5.1
**OS**: Windows 10[.0.18362.356] (WSL)

**Comment by lefou** [comment]
I can reproduce it.

**Comment by hmf** [comment]
I can also reproduce this (Mill: 0.5.1, Linux, JDK 11). Strange.  I am having a problem with another project (dynamic class loading) bu the tests are executed.

**Comment by lefou** [comment]
This is not a bug. The test class is not public. If you change class `HelloWorldTest` to public, the tests are found and executed.

**Comment by eyalroth** [comment]
@lefou I feel foolish now 😅 

Perhaps it's worth running non-public tests as well. One can easily omit the `public` keywords by mistake and never be aware of it, especially in a large project with many test classes. JUnit I believe does pick up non-public tests.

**Comment by lefou** [comment]
The used test adapter is open source. So, if you want to improve it ...

https://github.com/sbt/junit-interface
