### ISSUE TITLE
AppVeyor tests don't work

### ISSUE THREAD

**Issue by lefou** [lihaoyi/mill#700]
Either fix or disable them, otherwise GitHub PRs always fail to check.

**Comment by lefou** [comment]
We decided to disable them. https://gitter.im/lihaoyi/mill?at=5e256bbf0289c83ba2cc3af2

**Comment by lefou** [comment]
@lihaoyi Can you please disable AppVeyor builds. I don't have the permission to do it. And just removed the config file isn't enough.

**Comment by lihaoyi** [comment]
should be disabled now i think

**Comment by lefou** [comment]
Iteresting, it now still runs, but almost immediatly reports success.
