### ISSUE TITLE
junit.JUnitFramework with incorrect parameters fails silently

### ISSUE THREAD

**Issue by hmf** [lihaoyi/mill#713]
If you pass invalid parameters to the `test` command it fails silently - no tests are executed. For example: 

```
 mill -i graaljs.test error
```

gives me: 

```
Test run started
Test run finished: 0 failed, 0 ignored, 0 total, 0.001s
```

However this will work correctly:

```
 mill -i graaljs.test +v
```

Tested with Mill 0.5.1, JDK 11 + Linux

**Comment by lefou** [comment]
It looks like the first parameter is used to select a specific test case. But it has to be an exact match, so if you have no test case named "error" it will not execute any tests. This is almost the same behavior as we have for utest, except for 2 differences: utest will throw an exception if no test matches the argument, and utest matches also if you only give prefix.

**Comment by lefou** [comment]
But as I understand it, the handling of the parameters depends on the test framework. So it might be what a user is expecting from JUnit, right?

**Comment by hmf** [comment]
Don't know what users expect from JUnit. I was expecting the same behavior for both frameworks. But, yes you are right -  if Junit is matching/processing, then it will dictate what happens (for ex, no exceptions). I was thinking maybe the Mill framework wrapper was the culprit - but from your description its JUnit. 

Small note: that "error" is an argument to be passed to the JUnit test (like a command line argument). It is no an ID of a test. If I pass an invalid argument with the correct test ID it fails silently.  

Thanks for the feedback,
