### ISSUE TITLE
Refactor CoursierModule from JavaModule

### ISSUE THREAD

**Issue by lefou** [lihaoyi/mill#722]
Sometimes, one want's to resolve dependencies but does not need a full-blown Java/Scala Module, e,g. projects that only assemble deployments need to download/resolve but don't build sources in the classical sense.

It should be possible to split the `JavaModule` and move all Coursier-related stuff info a `CoursierModule` and the extends that in the `JavaModule`.

**Comment by lihaoyi** [comment]
sounds reasonable
