### ISSUE TITLE
mill.scalalib.GenIdea/idea error: -gt: unary operator expected MacOS

### ISSUE THREAD

**Issue by sergeda** [lihaoyi/mill#727]
When I try to run mill.scalalib.GenIdea/idea command on my Mac I got error:
```
/usr/local/Cellar/mill/0.5.2/libexec/mill: line 29: [: -gt: unary operator expected
/usr/local/Cellar/mill/0.5.2/libexec/mill: line 29: [: -ge: unary operator expected
```
I have MacOs Mojave installed

**Comment by lefou** [comment]
What's your default shell?

**Comment by sergeda** [comment]
> What's your default shell?

I have default shell: Bash

**Comment by lefou** [comment]
How do you've installed mill? What's the content of `/usr/local/Cellar/mill/0.5.2/libexec/mill`? It looks more like an issue with your distribution than one in mill.

**Comment by sergeda** [comment]
> How do you've installed mill? What's the content of `/usr/local/Cellar/mill/0.5.2/libexec/mill`? It looks more like an issue with your distribution than one in mill.

I've installed it using brew: ```brew install mill```
Here is content of the file:
```
#!/usr/bin/env sh

# This is a wrapper script, that automatically download mill from GitHub release pages
# You can give the required mill version with MILL_VERSION env variable
# If no version is given, it falls back to the value of DEFAULT_MILL_VERSION
DEFAULT_MILL_VERSION=0.5.2

set -e

if [ -z "$MILL_VERSION" ] ; then
  if [ -f ".mill-version" ] ; then
    MILL_VERSION="$(head -n 1 .mill-version 2> /dev/null)"
  elif [ -f "mill" ] && [ "$BASH_SOURCE" != "mill" ] ; then
    MILL_VERSION=$(grep -F "DEFAULT_MILL_VERSION=" "mill" | head -n 1 | cut -d= -f2)
  else
    MILL_VERSION=$DEFAULT_MILL_VERSION
  fi
fi

MILL_DOWNLOAD_PATH="$HOME/.mill/download"
MILL_EXEC_PATH="${MILL_DOWNLOAD_PATH}/$MILL_VERSION"

version_remainder="$MILL_VERSION"
MILL_MAJOR_VERSION="${version_remainder%%.*}"; version_remainder="${version_remainder#*.}"
MILL_MINOR_VERSION="${version_remainder%%.*}"; version_remainder="${version_remainder#*.}"

if [ ! -x "$MILL_EXEC_PATH" ] ; then
  mkdir -p $MILL_DOWNLOAD_PATH
  if [ $MILL_MAJOR_VERSION -gt 0 ] || [ $MILL_MINOR_VERSION -ge 5 ] ; then
    ASSEMBLY="-assembly"
  fi
  DOWNLOAD_FILE=$MILL_EXEC_PATH-tmp-download
  MILL_DOWNLOAD_URL="https://github.com/lihaoyi/mill/releases/download/${MILL_VERSION%%-*}/$MILL_VERSION${ASSEMBLY}"
  curl --fail -L -o "$DOWNLOAD_FILE" "$MILL_DOWNLOAD_URL"
  chmod +x "$DOWNLOAD_FILE"
  mv "$DOWNLOAD_FILE" "$MILL_EXEC_PATH"
  unset DOWNLOAD_FILE
  unset MILL_DOWNLOAD_URL
fi

unset MILL_DOWNLOAD_PATH
unset MILL_VERSION

exec $MILL_EXEC_PATH "$@"
```

**Comment by lefou** [comment]
Ah ok, it's the mill script found in the root of the repo.

Effectively the error means, the variable `MILL_VERSION` is invalid. Either you specified it as a environment variable `MILL_VERSION` or you have a `.mill-version` file or you have a `mill` script in your local directory with or without a `DEFAULT_MILL_VERSION` line in it. Can you please check if the provided value is correct?

**Comment by lefou** [comment]
Beside that, I think the script should quote the variables in the tests.

**Comment by sergeda** [comment]
> Ah ok, it's the mill script found in the root of the repo.
> 
> Effectively the error means, the variable `MILL_VERSION` is invalid. Either you specified it as a environment variable `MILL_VERSION` or you have a `.mill-version` file or you have a `mill` script in your local directory with or without a `DEFAULT_MILL_VERSION` line in it. Can you please check if the provided value is correct?

I don't have environment variable 'MILL_VERSION' and don't have file '.mill-version' and content of the mill script I've already posted.

**Comment by lefou** [comment]
Can you please run `sh -x /usr/local/Cellar/mill/0.5.2/libexec/mill` and post the output?

**Comment by sergeda** [comment]
> Can you please run `sh -x /usr/local/Cellar/mill/0.5.2/libexec/mill -i version` and post the output?

Sure.
```sh -x /usr/local/Cellar/mill/0.5.2/libexec/mill
+ DEFAULT_MILL_VERSION=0.5.2
+ set -e
+ '[' -z '' ']'
+ '[' -f .mill-version ']'
+ '[' -f mill ']'
+ MILL_VERSION=0.5.2
+ MILL_DOWNLOAD_PATH=/Users/sdashko/.mill/download
+ MILL_EXEC_PATH=/Users/sdashko/.mill/download/0.5.2
+ version_remainder=0.5.2
+ MILL_MAJOR_VERSION=0
+ version_remainder=5.2
+ MILL_MINOR_VERSION=5
+ version_remainder=2
+ '[' '!' -x /Users/sdashko/.mill/download/0.5.2 ']'
+ unset MILL_DOWNLOAD_PATH
+ unset MILL_VERSION
+ exec /Users/sdashko/.mill/download/0.5.2
Build repl needs to be run with the -i/--interactive flag```

**Comment by lefou** [comment]
Ok, this one looks good, but does not reproduce the initial error. Can you also post the output of `sh -x /usr/local/Cellar/mill/0.5.2/libexec/mill -i mill.scalalib.GenIdea/idea`?

**Comment by sergeda** [comment]
I can't reproduce error know. Don't know what was the cause of the problem but it's definitely not problem of Mill script. Thanks

**Comment by lefou** [comment]
> Beside that, I think the script should quote the variables in the tests.

Fixed
