### ISSUE TITLE
IntelliJ not picking ScalaPB generated sources

### ISSUE THREAD

**Issue by AlexITC** [lihaoyi/mill#728]
I have been facing an issue while using IntelliJ with mill and scalapb, for some reason, the autogenerated sources are not picked by IntelliJ and it's annoying to deal with it.

I have prepared a small project that should allow you to reproduce the behavior, in any case, I'm adding the details below.

Thanks.

## System:
- Mill `0.5.2-6-c3af02`
- Ubuntu 18.04
- IntelliJ:
```
IntelliJ IDEA 2019.2.2 (Community Edition)
Build #IC-192.6603.28, built on September 6, 2019
Runtime version: 11.0.3+12-b304.56 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
```

## How to reproduce:
- Clone https://github.com/AlexITC/mill-scalapb-intellij-test
- Run `mill app.compile` and then `mill mill.scalalib.GenIdea/idea`.
- Open the folder with IntelliJ
- Navigate to the `Example.scala` file, the `protos.ProtoMsg` is in red cause IntelliJ can't resolve it (see screenshot 1).
- Tap shift key twice, and look for the `ProtoMsg` IntelliJ is able to find the generated source (see screenshot 2).

## Screenshots:
- IntelliJ not picking the generated source: ![Screenshot from 2019-11-04 20-50-01](https://user-images.githubusercontent.com/4218436/68177342-3e074180-ff45-11e9-9c43-34d439252b4c.png)

- IntelliJ finding the right generated source: ![Screenshot from 2019-11-04 20-50-36](https://user-images.githubusercontent.com/4218436/68177354-43648c00-ff45-11e9-8900-0d647190e19f.png)

**Comment by lefou** [comment]
I guess the issue is, that the generated folder is not a child path of the content url.

The currently generated idea module file contains the following source folders:

```xml
        <content url="file://$MODULE_DIR$/../app">
            <sourceFolder url="file://$MODULE_DIR$/../app/src" isTestSource="false"/>
            <sourceFolder url="file://$MODULE_DIR$/../out/app/compileScalaPB/dest" isTestSource="false" generated="true"/>
            <sourceFolder url="file://$MODULE_DIR$/../app/resources" type="java-resource"/>
            <excludeFolder url="file://$MODULE_DIR$/../app/target"/>
        </content>
```

whereas it should possibly look like this:

```xml
    <content url="file://$MODULE_DIR$/../app">
      <sourceFolder url="file://$MODULE_DIR$/../app/src" isTestSource="false" />
      <sourceFolder url="file://$MODULE_DIR$/../app/resources" type="java-resource" />
      <excludeFolder url="file://$MODULE_DIR$/../app/target" />
    </content>
    <content url="file://$MODULE_DIR$/../out">
      <sourceFolder url="file://$MODULE_DIR$/../out/app/compileScalaPB/dest" isTestSource="false" generated="true" />
    </content>

```
