### ISSUE TITLE
Foreign modules which alter millSourcePath can result in non-unique output paths

### ISSUE THREAD

**Issue by ajrnz** [lihaoyi/mill#743]
Foreign modules which alter `millSourcePath` can result in non-unique output paths. This is the cause of a unwanted recompilations of a library which had not been modified. The output path of `js` and `jvm` submodules was being mapped to the same directory causing mill to make the unnecessary recompilations.

The setup is like this:
```scala
object commonlib extends Module {
  object jvm extends ScalaModule
    def millSourcePath = commonlib.millSourcePath
    def sources = T.sources( millSourcePath / "src", millSourcePath / "src-jvm" )
  }
  
  object js extends ScalaJSModule {
    def millSourcePath = commonlib.millSourcePath
    def sources = T.sources( millSourcePath / "src", millSourcePath / "src-js" )
  }
}
```

so that you have source directories of the form
```
commonlib/src/
commonlib/src-jvm/
commonlib/src-js/
```

and targets
```
commonlib.js.compile
commonlib.jvm.compile
```

Then in another project you reference the `commonlib.js` and `commonlib.js` module.

```scala
import $file.^.common.{build => commonlibbuild}, commonlibbuild.commonlib

object client extends ScalaJSModule {
  def moduleDeps = Seq(commonlib.js)
  ...
}

object server extends ScalaModule {
  def moduleDeps = Seq(commonlib.jvm)
  ...
}
```

Then the output directories in this project for `commonlib.js` and `commonlib.js` will be identical.
This is because `ctx.millSourcePath` is used as part of the path for foreign modules - not the segmented path name (see `destSegments()` in `Evaluator.scala`). 

It would be better to encode this as just the labeled task segments relative to the root of the foreign module as is done with non-foreign modules however it is not obvious how to get the root of a foreign module when just given a task (see `destSegments()`). One option might be to change `foreign` boolean of `Ctx` to be an `Option[Path]` which points to the root of a foreign module. 

Happy to do a PR if the approach is ok.

**Comment by lihaoyi** [comment]
Everything here sounds reasonable. @Baccata you implemented the foreign modules logic if I recall correctly; what do you think?

**Comment by ajrnz** [comment]
I did a PR (#744) for this using `Option[Segments]`. Works for my case and passes  the tests.

**Comment by Baccata** [comment]
The proposed approach sounds good to me :+1:

**Comment by lihaoyi** [comment]
Thanks for the review @Baccata !
