### ISSUE TITLE
bsp failed to generate corrent `ivyDeps` in sub-modules

### ISSUE THREAD

**Issue by sequencer** [lihaoyi/mill#745]
```
import mill._
import scalalib._
import publish._
import $ivy.`com.lihaoyi::mill-contrib-bsp:$MILL_VERSION`

object myproj extends ScalaModule {
  def scalaVersion = "2.12.10"

  override def ivyDeps = Agg(
    ivy"com.lihaoyi::os-lib:0.4.0",
    ivy"com.lihaoyi::upickle:0.8.0",
  )

  object tests extends Tests {
    def ivyDeps = Agg(
      ivy"com.lihaoyi::ammonite-ops:1.8.1",
      ivy"com.lihaoyi::utest:0.7.2"
    )

    def testFrameworks = Seq("utest.runner.Framework")
  }
}
```
`ammonite` and `utest` can not be accessed by Intellij.

**Comment by sequencer** [comment]
@samvel1024 @samvel1024 this issue may need your help.
I didn't found test for currently bsp flow. Thus it's hard for me to dive into this.

**Comment by samvel1024** [comment]
@sequencer Thanks for reporting. I will try to figure this out by the end of the week.

**Comment by samvel1024** [comment]
I tried to reproduce the issue with no significant luck. For me IntelliJ was able to correctly identify source jars and handle references to upickle for example. I think I don't fully understand what you mean by `bsp fails to generate ivy deps`. 

Can you please enable bsp trace log (in bsp settings), import the project from scratch and provide the log file generated in `$INSTALL_DIR/system/log/bsp/` where install dir is usually something like `~/.IntelliJIdea<VERSION>`. To make sure we work on the same project please do the above steps for the following example project `https://github.com/samvel1024/build_test_projects/tree/master/mill1`. It already has the build definition that you have provided.

**Comment by sequencer** [comment]
quite strange, I'll look back into this later this weak.
