### ISSUE TITLE
Investigate Mill vs SBT performance

### ISSUE THREAD

**Issue by lihaoyi** [lihaoyi/mill#75]
My own subjective feeling is that Mill is slower at the watch-edit-recompile-test workflow than SBT is. Previously this was largely due to Mill not keeping around warm copies of Scalac, but that should have been fixed already. Another point is that Mill doesn't currently run independent tasks in parallel, while SBT does.

This task is to investigate the relative performance of Mill vs SBT at the common watch-edit-recompile-test, to understand what the performance differences are and exactly what is causing them. There's no fundamental reason we should be any slower, and understanding our performance is the first step in making sure we're up to par

**Comment by japgolly** [comment]
What's the resolution of this issue? I saw the new doc's but didn't see anything on performance in relation to SBT.

**Comment by dos65** [comment]
I tried to do some minor measures about a month ago.
At least there was the significant difference on startup time ( I used `show scalaVersion` command and empty project setup) :
- sbt (1.0.0+) - 17-20 seconds constantly
- mill  - 7 seconds on the first run and 1 second after caching build file.

**Comment by japgolly** [comment]
Sounds awesome, thanks!
