### ISSUE TITLE
[IntelliJ] Support SHARED_SOURCES_MODULE

### ISSUE THREAD

**Issue by frobinet** [lihaoyi/mill#825]
It's not clear from the documentation how to create shared sources modules in the same way the SBT are usually setup, ie. having `shared`, `js` and `jvm` modules. 

In this setup, the `shared` folder is usually not marked as a `JAVA_MODULE` for IntelliJ, but as `SHARED_SOURCES_MODULE`. 

Right now, `GenIdea` will only create `JAVA_MODULE` modules. Manually editing the module file produced by GenIdea works, but compilation within IntelliJ doesn't work anymore:

```
Error:scala: IDEA incremental compiler cannot handle shared source modules: shared.
Please enable sbt incremental compiler for the project.
```

I'm not sure if there is a Mill setting I could tweak to make this work. 

In the meantime, my solution is:

```
object shared extends CommonSettings
object jvm extends ScalaModule with CommonJVMSettings
object js extends CommonJSSettings
```

**Comment by lefou** [comment]
Shared sources can just be added as sources of multiple modules. This will also work with GenIdea since mill 0.6.3 when the shared source folder is not a sub-folder of the module.
