### ISSUE TITLE
T.source does not update when its contents have changed

### ISSUE THREAD

**Issue by zainab-ali** [lihaoyi/mill#832]
A detailed reproduction is at https://github.com/zainab-ali/mill-source

I expect the downstream target to update when the contents of the upstream `T.source` are modified.

This project contains two targets:

 - `first` is the upstream source.  It points to the `first.txt` file.  It should be re-calculated whenever `first.txt` is modified.
 - `second` is a downstream target.  It should also be re-run whenever `first.txt` is modified.

## Steps to reproduce

1 . Run

```
$ mill -w myModule.second
[2/2] myModule.second
The first.txt file was modified
Watching for changes to 0 dirs and 2 files... (Ctrl-C to exit)
```

2. Modify the `first.txt` file

## Observed behaviour

 - The contents of `out/myModule/first/meta.json` are not modified
 - The text `The first.txt file was modified` is not printed.

## Expected behaviour

 - The contents of `out/myModule/first/meta.json` should be modified
 - The text `The first.txt file was modified` should be printed.

**Comment by lefou** [comment]
I can reproduce

**Comment by lefou** [comment]
If I understand correctly, we rely on the reported `interp.watchedFiles` from underlying ammonite.

**Comment by lihaoyi** [comment]
IIRC Mill has two subsystems for watching files: the one that watches `T.sources` and re-runs tasks, and the one that involves Ammonite's `interp.watch` (and now `interp.watchValue`) that re-compiles (if necessary) and re-evaluates the `build.sc` file and dependencies. I don't remember how these two systems interact; perhaps somewhere in `RunScript.scala`?

**Comment by lefou** [comment]
I just changed to `T.sources` and this works as expected. So, it's specific to `T.source`, which is quite new.

**Comment by lihaoyi** [comment]
Should be fixed in master; another related issue is that `T.input`s are not currently being watched. Fixing that would be slightly more invasive than the trivial fix for `T.source`, so I left it for later if anyone wants to pick that up
