### ISSUE TITLE
mill 0.6.2 breaks bsp

### ISSUE THREAD

**Issue by sequencer** [lihaoyi/mill#833]
When I use idea import project as bsp in 0.6.2.
IDEA said:
```
Problem executing BSP job
```
In 0.6.1, it works.
There is no debug information in `bsp.log`.

**Comment by YingLiu4203** [comment]
This may help
`` import $ivy.`com.lihaoyi::mill-contrib-bloop:$MILL_VERSION` ``

**Comment by sequencer** [comment]
> This may help
> `` import $ivy.`com.lihaoyi::mill-contrib-bloop:$MILL_VERSION` ``

Still no luck :(

**Comment by lefou** [comment]
What about adding the following?

```scala
import $ivy.`com.lihaoyi::mill-contrib-bsp:$MILL_VERSION`
```

I even don't know what you are using, as both contrib-bsp and contrib-bloop provide BSP.

**Comment by joan38** [comment]
This is fixed now and can be closed
