### ISSUE TITLE
mill fails to run in fish shell

### ISSUE THREAD

**Issue by jtjeferreira** [lihaoyi/mill#834]
Installed mill in arch linux and when running it in fish shell I got this error:

```
$ mill
Failed to execute process '/usr/bin/mill'. Reason:
exec: Exec format error
The file '/usr/bin/mill' is marked as an executable but could not be run by the operating system.
```

Googling the error, I found this https://github.com/fish-shell/fish-shell/issues/4946 which suggest the file is missing a shebang...

Here is the first lines of `/usr/bin/mill`:

```
@ 2>/dev/null # 2>nul & echo off & goto BOF^M
:
if [ -z "$JAVA_HOME" ] ; then
  JAVACMD="java"
else
  JAVACMD="$JAVA_HOME/bin/java"
fi
case "$1" in
```

Adding `#!/bin/bash` fixes the problem

**Comment by lefou** [comment]
But wouldn't adding a shebang hinder the current magic to also run under Windows as BATCH script?

**Comment by lefou** [comment]
> But wouldn't adding a shebang hinder the current magic to also run under Windows as BATCH script?

Sorry for posting that question to which I actually know the answer to. 

This first line is important to make this file header work as a script in most linux shells (except zsh) _and_ Windows cmd shell. 
Under zsh you may want to use you own wrapper script, or the one provied with mill itself (`./mill`,  only work for non-Windows) or /* shameless plug */ use https://github.com/lefou/millw.

**Comment by lefou** [comment]
Closing this as it is by-design.
