### ISSUE TITLE
mill's standalone standalone executable jar should support run with Windows' CMD.

### ISSUE THREAD

**Issue by hepin1989** [lihaoyi/mill#84]
![image](https://user-images.githubusercontent.com/501740/34420932-42d91016-ec47-11e7-94ed-859cb64ac8fb.png)

**Comment by lihaoyi** [comment]
Given that WSL/Ubuntu seems like the future, I'm going to punt on this and call it a wontfix. If someone wants to contribute it that's great, but I don't think we should spend time here
