### ISSUE TITLE
scalapblib resolves scalapbc_2.12 in 2.13 builds of mill

### ISSUE THREAD

**Issue by heksesang** [lihaoyi/mill#846]
In the post-0.6.2 builds of mill that are built on 2.13, `compileScalaPB` fails because the `ScalaPBModule` uses 2.12.4 as target version when it resolves the `scalapbc` dependency:

```scala
def scalaPBClasspath: T[Loose.Agg[PathRef]] = T {
  resolveDependencies(
    Seq(
      coursier.LocalRepositories.ivy2Local,
      MavenRepository("https://repo1.maven.org/maven2")
    ),
    Lib.depToDependency(_, "2.12.4"),
    Seq(ivy"com.thesamet.scalapb::scalapbc:${scalaPBVersion()}")
  )
}

```

This should be fixable by replacing the hardcoded `"2.12.4"` with `scalaVersion()`, I think.

**Comment by lefou** [comment]
What's really needed here is the Scala version with which mill is running. I have no idea, how we can detect that at runtime? Maybe, we should provide some API in Mill to get access to these info.

**Comment by heksesang** [comment]
Then there are two approaches I can see:

1) Add the scala version used to compile as a target (or something like the $MILL_VERSION) in the assembly.

2) Detect "features" in the Scala API by the use of reflection and use those to determine the version of Scala that is currently loaded in the classpath.

Until that is in place, we should just bump the version here so that it at least runs.
