### ISSUE TITLE
Mill is adding the scala compiler as a compiler plugin, seem to make problems for metals

### ISSUE THREAD

**Issue by scalavision** [lihaoyi/mill#880]
I opened this issue in metals, but it seems the problem might be in mill.

Could you please have a look at:

https://github.com/scalameta/metals/issues/1720

I've been a happy user of `mill` for some time now. I think it is the best build tool in Scala!

**Comment by lefou** [comment]
Looks like an unfortunate transitive dependency setup. I commented on scalameta/metals#1720. If that's doesn't fix your issue, please reopen this ticket.
