### ISSUE TITLE
MavenRepository doesn't handle local repository

### ISSUE THREAD

**Issue by tballard** [lihaoyi/mill#891]
Maven metafile name is maven-metafile.xml or maven-metadata-<repo-id>.xml for a repository with repo-id identiier. The MavenRepository class makes no attempt to handle the latter case, failing with "not found: /Users/tballard/.m2/repository/org/redangus/reds_da/maven-metadata.xml" when there is a perfectly good maven-metadata-local.xml available.

**Comment by alexarchambault** [comment]
@tballard That's more an issue with [coursier](https://github.com/coursier/coursier), that mill uses to fetch dependencies.

**Comment by alexarchambault** [comment]
Don't hesitate to open issue about it there.

**Comment by lefou** [comment]
Closing this, as it is an upstream issue and TBH I can't see what the really means for mill. Feel free to comment/reopen with an concrete use case which does not work because of it. Also, if you know any workaround, please document it here for others. Thanks!
