### ISSUE TITLE
Support for ScalaJS 1.1.0

### ISSUE THREAD

**Issue by lavrov** [lihaoyi/mill#894]
After bumping ScalaJS to `1.1.0`:

```
[4/72] client.scalaJSWorkerClasspath 
1 targets failed
client.scalaJSWorkerClasspath 
Resolution failed for 1 modules:
--------------------------------------------
  com.lihaoyi:mill-scalajslib-worker-1.1_2.13:0.7.0 
	not found: /Users/vlavrov/.ivy2/local/com.lihaoyi/mill-scalajslib-worker-1.1_2.13/0.7.0/ivys/ivy.xml
	not found: https://repo1.maven.org/maven2/com/lihaoyi/mill-scalajslib-worker-1.1_2.13/0.7.0/mill-scalajslib-worker-1.1_2.13-0.7.0.pom
	not found: https://oss.sonatype.org/content/repositories/releases/com/lihaoyi/mill-scalajslib-worker-1.1_2.13/0.7.0/mill-scalajslib-worker-1.1_2.13-0.7.0.pom
```

**Comment by lefou** [comment]
Can you please try to articulate the issue?

**Comment by lavrov** [comment]
ScalaJS 1.1.0 was [released](https://www.scala-js.org/news/2020/05/18/announcing-scalajs-1.1.0/). I tried to switch to this version in one of my projects and got the error above. The missing `mill-scalajslib-worker-1.1_2.13:0.7.0` doesn't seem to be [published(https://search.maven.org/search?q=mill-scalajslib-worker).

**Comment by lefou** [comment]
Ah ok. I think ScalaJS 1.x artifacts are compatible to each other. So there must be some other issue here. We need to investigate.

**Comment by lefou** [comment]
As a workaround you can override `scalaJSWorkerVersion` in your build.

**Comment by davesmith00000** [comment]
>Ah ok. I think ScalaJS 1.x artifacts are compatible to each other. 
I believe that isn't the case, see below:

Trying to pull a Scala.js `1.1.0` lib into a mill build for `1.0.1` results in the following error:

```
Linker: 46357 us
1 targets failed
foo.fastOpt org.scalajs.ir.IRVersionNotSupportedException: Failed to deserialize a file compiled with Scala.js 1.1 (supported up to: 1.0)
(..)
org.scalajs.ir.IRVersionNotSupportedException: This version (1.1) of Scala.js IR is not supported. Supported versions are up to 1.0
```

**Comment by davesmith00000** [comment]
I snooped around a little further on my flavour of the problem, not @lavrov's but they're related I think, and it looks like Scala.js is _only_ backwards compatible on minor versions (unless I'm looking at the wrong part of the Scala.js code - quite possible!), which makes sense but it isn't what people might expect in Scala libraries:

https://github.com/scala-js/scala-js/blob/abb40e0957f8f296637b0aa79bf2db2dc044cabb/ir/src/main/scala/org/scalajs/ir/ScalaJSVersions.scala#L68

In the last release a PR when in that talks about this - I'm sure the PR is fine - but there's a nice comment that mentions they run the IR checker on the first pass of the linker:

https://github.com/scala-js/scala-js/pull/3972

The reason I'm saying all this is that I was wondering if you think that means the workaround you suggest is really compatible?

**Comment by davesmith00000** [comment]
Is there any value in me attempting a PR? I'm naively assuming it's version bumping and/or cross building?

**Comment by lefou** [comment]
Oh, I think we've already solved this issue. Could you have a look at #921 and check if it fixes your issue too? It should be in mill snapshot release `0.7.3-14-14db46` and later. For info how to use these versions have a look at http://www.lihaoyi.com/mill/#development-releases.

**Comment by davesmith00000** [comment]
Ah excellent! I'll give it a shot soon as I can - thanks!

**Comment by davesmith00000** [comment]
@lefou Not quite. Works for Scala.js `1.1.0` but not `1.1.1` because `scalajs-env-jsdom-nodejs_2.13:1.1.1` has not been published. Here's the error:

```
1 targets failed
(...).scalaJSLinkerClasspath
Resolution failed for 1 modules:
--------------------------------------------
  org.scala-js:scalajs-env-jsdom-nodejs_2.13:1.1.1
```

In the PR you attached, I think the offending line (which wasn't changed in the PR btw) is:

```
def scalaJSWorkerClasspath = T {
  (..)
  ivy"org.scala-js::scalajs-env-jsdom-nodejs:${scalaJSVersion()}"
```

**Comment by davesmith00000** [comment]
Looks like it's been fixed in a more recent commit:
https://github.com/lihaoyi/mill/blob/master/scalajslib/src/ScalaJSModule.scala#L56

**Comment by davesmith00000** [comment]
8 hours ago!
https://github.com/lihaoyi/mill/commit/b32df318a60a39e0b7b09557cbd3c4e52ae4c7e6

**Comment by lefou** [comment]
It's always hard to support future releases. But we improve in small steps. ;-)
