### ISSUE TITLE
Watch mode doesn't handle new files

### ISSUE THREAD

**Issue by dos65** [lihaoyi/mill#93]
Currently  `watch` mode (`mill --watch proj.compile `) reacts only on changes from existed at startup moment files.
At least it should react on file creation. I'm not sure about removing, maybe there are some inotify limitations (comparing to sbt - it reacts on new files, but ignore removing)

**Comment by lihaoyi** [comment]
We use a while-loop `stat`ing files and listing folders in a loop, so there's no reason we shouldn't be able to react to any and all changes

**Comment by lihaoyi** [comment]
I am unable to reproduce this. `sbt "~bin/test:run --watch core.compile"` seems to correctly pick up the creation of new `foo.scala` files within the `core/src/main/scala/mill` folder

**Comment by dos65** [comment]
You right - I can't reproduce it too now. Maybe there were some changes from yesterday

**Comment by lihaoyi** [comment]
I bumped into a bug with `--watch` not properly handling changes in `build.sc` if a watch-rerun triggers while `build.sc` did not changed, will push a fix after `test.sh` finishes
