### ISSUE TITLE
Generic Reusable Module as the Base Module

### ISSUE THREAD

**Issue by sirinath** [lihaoyi/mill#942]
Writing a new module requires a reasonable amount of work and knowledge of Mill internals and API. So is it possible to have a more generic module where one can:
- implement a method to provide the compile command
- similarly for tests and 
- other tasks

If command-line tools are invoked, OS-specific command list if there is a variation. Source lists, dir lists, lib paths, etc. can be made available with OS-specific file separators so more generic command strings can be written. Also, library-based/API-based tools can be evoked. 

This will bring down the barrier to add new test runners, code coverage tools and compilers where the user specifies the bear minimal boilerplate to make it work without the need of new plugins or modules to be written.

Language-specific modules just "inject" the bare minimal to compiler and tools to work. The majority of the code in these modules ideally should be just these command lists, for clarity, with the plumbing handled elsewhere.

**Comment by sirinath** [comment]
@lihaoyi Let me know what additional information you might want.

E.g. I want to set up TestNG testing without writing a plugin.

**Comment by lefou** [comment]
@sirinath In the first comment you make a very abstract claim which I think @lihaoyi isn't able to reconstruct. Me neither. In fact, writing new modules is very easy and doesn't require any deep knowledge of mill besides the documentation. So I think you need to be more specific about your issues. Probably you want to ask in the Gitter channel first.

Setting up TestNG is documented (http://www.lihaoyi.com/mill/page/contrib-modules.html#testng). I think you also need to add the testng contrib module to the `ivyDeps` though.

**Comment by sirinath** [comment]
When looking at https://github.com/lihaoyi/mill/blob/3f1f1856c7d9af1e8d269d9dd80a2a8cf0f5f243/scalalib/src/JavaModule.scala what I was expecting is the module will mainly just have (1) build of the classpath (2) `javac` command (3) Javadoc commands (4) Jar commands (5) dependency downloading (6) testing, in a very simple way. Essentially these are there but a lot of the plumbing is also exposed.

**Comment by lefou** [comment]
But it isn't that simple and if you need to support more complicated cases, your have an easy way to re-plumb exactly what you want. Also, in contrary to your implication, the complexity is not smaller in other tools. E.g. in Maven you also have much more steps than only the ones you mentioned, but still you'll have a hard time to adapt the workflow. The thing is, if you just want to replace the compiler in mill, just override the `compile` target. If you want to override the packaging, override `jar` step, and so on. It's the easiest experience I've ever seen under all build tools targeting the JVM.

**Comment by sirinath** [comment]
OK. This is the 1st time I have looked into the code of any Build tool. Anyway, what I felt is that some of the code here can be refactored into traits leaving just the Java-specific stuff in the Java module. E.g. dependency management, managing classpath, jars, etc. may be used by other JVM languages. So they can be in smaller sized traits. Also perhaps there can be an abstract module leaving just the compile and language-specific items as abstract and finally implemented in Java module.

**Comment by lihaoyi** [comment]
In general, the issue tracker is for issues, not for questions. It’s great to discuss these things, but such discussion should go in the gitter channel
