### ISSUE TITLE
dotty 0.26.0-RC1, mill 0.8.0: cannot find main when using main functions

### ISSUE THREAD

**Issue by aappddeevv** [lihaoyi/mill#957]
I found that with this dotty release, the main class was not automatically found whereas in 0.7.3 and previous version of dotty it was found. I had to add `def mainClass = Option("mymain.run")` to the build file under the above versions.

**Comment by lefou** [comment]
Can you provide a small example to reproduce?

**Comment by lefou** [comment]
Works for me.

```
$ mill all version example1.run
[1/37] version 
0.8.0
[27/37] example1.compile 
[info] Compiling 1 Scala source to /tmp/mill-957/out/example1/compile/dest/classes ...
[info] Done compiling.
[37/37] example1.run 
example1
```

This is my dir layout:

```
$ tree .
.
├── build.sc
└── example1
    └── src
        └── example1.scala
```

Do you have more than one main defined?

**Comment by aappddeevv** [comment]
Not in the example1 project. Having said that, I wonder if the out dir was not cleared as I had potentially did at one point have another main defined that was compiled.

If there was more than one main would it report that it could not find a main vs reporting there is more than one main?

**Comment by lefou** [comment]
It would say something like: "Multiple main classes found [...] please explicitly specify which one to use by overriding mainClass"

**Comment by lefou** [comment]
Closing this one. If you have any idea want went wrong and the issue re-appears, feel free to comment / re-open this ticket.
