### ISSUE TITLE
empty project dumps stack

### ISSUE THREAD

**Issue by tballard** [lihaoyi/mill#966]
First, your contribution to the scala ecosystem is greatly appreciated.

The build.sc consists of these 2 lines and yet mill results in a stack trace with no meaningful error message.

import mill.scalalib._
object util extends MavenModule { }

Clearly any stack trace is a bug unless you are try to elicit error reports so here you are. An unknown problem reading some unknown file is not overly helpful. 

> mill util.compile
Compiling /Users/tballard/git/redspro/build.sc
[5/17] util.sources
1 targets failed
util.sources java.nio.file.FileSystemException: /Users/tballard/git/redspro/util/src/main/java/out/mill-worker-ojc5RWiGDh20TNFS6Wxs8ik2jt0=-1/io: Operation not supported on socket
    java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:100)
    java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
    java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
    java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219)
    java.base/java.nio.file.Files.newByteChannel(Files.java:373)
    java.base/java.nio.file.Files.newByteChannel(Files.java:424)
    java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:420)
    java.base/java.nio.file.Files.newInputStream(Files.java:158)
    os.Path.getInputStream(Path.scala:474)
    os.read$inputStream$.apply(ReadWriteOps.scala:231)
    mill.api.PathRef$.$anonfun$apply$2(PathRef.scala:40)
    mill.api.PathRef$.$anonfun$apply$2$adapted(PathRef.scala:30)
    scala.collection.IterableOnceOps.foreach(IterableOnce.scala:553)
    scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:551)
    scala.collection.AbstractIterable.foreach(Iterable.scala:920)
    scala.collection.IterableOps$WithFilter.foreach(Iterable.scala:890)
    mill.api.PathRef$.apply(PathRef.scala:30)
    mill.scalalib.MavenModule.$anonfun$sources$22(MiscModule.scala:61)
    mill.api.Result$Success.map(Result.scala:28)
    mill.api.Result$Success.map(Result.scala:27)
    mill.scalalib.MavenModule.$anonfun$sources$20(MiscModule.scala:61)
    mill.define.Applicative$Applyer.$anonfun$zipMap$1(Applicative.scala:35)
    mill.define.Task$MappedDest.evaluate(Task.scala:392)

**Comment by lefou** [comment]
Looks like a duplicate to #823.

**Comment by lefou** [comment]
To clarify: This happens, if mill finds some socket files in one of the configured source folders.

**Comment by dwalend** [comment]
Would it be distasteful to have mill walk the directories toward root until it finds the bulid.sc ?

**Comment by lefou** [comment]
> Would it be distasteful to have mill walk the directories toward root until it finds the bulid.sc ?

IMHO, yes. But writing a simple wrapper script that searches upwards is rather easy.

**Comment by dwalend** [comment]
The other reasonable fix is to error out - without polluting the tree with a new /out/ directory. 

Would you consider reopening this ticket?

**Comment by lefou** [comment]
This is a duplicate to #823. Either comment there or create a new discussion.
