### ISSUE TITLE
v0.8.0: interactive mode not working

### ISSUE THREAD

**Issue by mkotsbak** [lihaoyi/mill#977]
$ mill -i
-i/--interactive/--repl/--no-server must be passed in as the first argument

This is a regression since 0.7.4.

**Comment by lefou** [comment]
Can you be more specific? How have you installed mill?

**Comment by lihaoyi** [comment]
Going to close this as not a proper issue. @mkotsbak feel free to open another one once you have more details, or ask in the gitter chat if you need help

**Comment by mkotsbak** [comment]
Installed through coursier.

**Comment by lefou** [comment]
> Installed through coursier.

I'm not sure if there is only "one" method to install via coursier, nevertheless, coursier installations are know to have issues and are unsupported. Please follow the official installation documentation (or use https://github.com/lefou/millw). I'm pretty sure the issue will vanish then.
