### ISSUE TITLE
v0.8.0: "No main class specified or found"

### ISSUE THREAD

**Issue by mkotsbak** [lihaoyi/mill#978]
Please don't open issues for questions, but ask in our gitter channel at https://gitter.im/lihaoyi/mill
[project].finalMainClass No main class specified or found

This is a regression since 0.7.4.

**Comment by lefou** [comment]
Can you be more specific? Do you have a main class in your project? Can you share your `build.sc`?

**Comment by lihaoyi** [comment]
Going to close this as not a proper issue. @mkotsbak feel free to open another one once you have more details

**Comment by mkotsbak** [comment]
This looks like is the issue: https://github.com/coursier/apps/issues/56
