### ISSUE TITLE
[BSP] - Missing `build/taskFinish`

### ISSUE THREAD

**Issue by ckipp01** [lihaoyi/mill#988]
A bit related to https://github.com/lihaoyi/mill/issues/987 but also a bit different is that it at the moment Mill doesn't have [compile-notifications](https://build-server-protocol.github.io/docs/specification.html#compile-notifications). I'll quote from this great explanation from Olaf in the Scala Contributors forum.

> compile progress notifications, Metals relies on BSP compile progress notifications (https://build-server-protocol.github.io/docs/specification.html#compile-notifications) in order to know when to update indexes, restart the presentation compiler, display progress bars for the user in the status bar and tree views.

The relevant thread starts [here](https://contributors.scala-lang.org/t/build-server-protocol-in-sbt/4234/17)

So basically we'd expect something like this, which is an example from Bloop:

```
[Trace - 06:03:42 PM] Received notification 'build/taskFinish'
Params: {
  "taskId": {
    "id": "3"
  },
  "eventTime": 1603991022406,
  "message": "Compiled \u0027MillTester\u0027",
  "status": 1,
  "dataKind": "compile-report",
  "data": {
    "target": {
      "uri": "file:/Users/ckipp/Documents/scala-workspace/mill-tester/MillTester/?id\u003dMillTester"
    },
    "errors": 0,
    "warnings": 0,
    "isNoOp": true,
    "isLastCycle": true,
    "clientDir": "file:///Users/ckipp/Documents/scala-workspace/mill-tester/.bloop/out/MillTester/bloop-bsp-clients-classes/classes-Metals-oA3DnvH8RFaQprwm5dzvRA\u003d\u003d/",
    "analysisOut": "file:///Users/ckipp/Documents/scala-workspace/mill-tester/.bloop/out/MillTester/MillTester-analysis.bin"
  }
}
```
And as an example, here you can see the progress bar still going, even though the compilation has been finished, but no `buid/taskFinish` received.

<img width="245" alt="Screenshot 2020-10-29 at 18 09 58" src="https://user-images.githubusercontent.com/13974112/97608023-12ad1a80-1a12-11eb-8e1a-b1e14e71e1ab.png">

**Comment by sequencer** [comment]
Possible to add a new version or back port to 0.9.3? Since some Linux distributions need to get this fix in. Now Intellij 2020.3 totally breaks mill.

**Comment by joan38** [comment]
@sequencer Use version `0.9.3-16-4c6cc4`
