### ISSUE TITLE
Invalid build definition to compile Mill with Bloop

### ISSUE THREAD

**Issue by ckipp01** [lihaoyi/mill#990]
Following the instructions on the [website about Bloop](https://www.lihaoyi.com/mill/page/contrib-modules.html#bloop) and then generating the `.bloop` directory with `mill mill.contrib.Bloop/install`,  Bloop is unable to build Mill. The same happens when you try building Bloop Mill using Metals.

The `bsp` module seems to not have the correct `moduleDeps` or `compileModuleDeps` as the `.bloop/bsp.json` has an empty array for `Dependencies` when I'm assuming it needs to depend on `main` or some subset of it. This causes all `mill` namespace stuff to not be found in the `bsp` module.

### Steps to reproduce this

1. Follow the Bloop quick start guide [on the website](https://www.lihaoyi.com/mill/page/contrib-modules.html#bloop)
2. After the Bloop install has finished, execute a `bloop compile bsp`
3. See all the errors

**Comment by lefou** [comment]
This is probably related to #955 and #964? There is probably no test present that catches the missing effect of `compileModuleDeps`.

**Comment by lefou** [comment]
It would be nice if somebody can verify, that #995 fixes the issue. /cc @ckipp01

**Comment by ckipp01** [comment]
> It would be nice if somebody can verify, that #995 fixes the issue. /cc @ckipp01

I'm a bit ignorant on the best way to do this. How do I correctly build and test it? I've followed the instructions [here in the readme](https://github.com/lihaoyi/mill#bootstrapping-building-mill-with-your-current-checkout-of-mill) and did the following:

- checked out your branch
- Did a `ci/publish-local.sh`
- Added in the newly created `mill-contrib-bloop` import to the `build.sc` file
- Tried to use the `./mill-release`, but I just keep getting 

```
❯ ./mill-release -version
Failed to execute process './mill-release'. Reason:
exec: Exec format error
The file './mill-release' is marked as an executable but could not be run by the operating system.
```
Is there a more detailed contributing guide that I may have missed?

**Comment by lefou** [comment]
@ckipp01, your are probably using a zsh or fish? I guess, the script needs a proper shebang then. It's designed to work on bash/sh and Windows cmd.

**Comment by lefou** [comment]
You can also try `sh ~/mill-release --version`.

**Comment by ckipp01** [comment]
👍 cool, that worked. Indeed I'm using fish, so that explains it.

I was able build #995, export all the `.bloop/` files and ensure that indeed everything compiles now. Looks like that does the trick!

**Comment by ckipp01** [comment]
So I think this might have regressed again. For example in the current `main` branch if you do the following:

```
./mill --import ivy:com.lihaoyi::mill-contrib-bloop: mill.contrib.Bloop/install
```
Then attempt to build for example contrib.bloop with Bloop, it will fail with a whole chain of errors. It looks like it can't find anything under `mill.`

**Comment by lefou** [comment]
@ckipp01 Could you please check with Mill 0.10.3? It that version works, it would be very helpful if you could post the generated (correct) file vs. the new generated (incorrect) file. I don't use bloop and I have no local bloop installation, so it's hard for me to reproduce. But these outputs might help me (or others) to understand the issue and write a test case too.

**Comment by lefou** [comment]
I think a proper implementation for the classpath and runtimeClasspath to be used in Bloop should not hand-roll the same logic found in `JavaModule` and `ScalaModule` but instead it should re-use the `bspCompileClasspath` target, which is already exactly doing this (and is meant to be an maintained astraction to be used by BSP). It returns an `UnresolvedPath`, which is either a local path (which can be re-used in Bloop, e.g. a resolved depenency) or a path relative to another target. E.g. the compiler output of a dependencies is some `classes/` sub path inside the dest dir of that compile target. When generating the Bloop config, we need to map these unresolved paths to the real compile output paths Bloop used for these module. All information should be already present in the `BloopImpl` to implement this mapping. But it's not a trivial change, so I won't do it right now.

**Comment by lefou** [comment]
@ckipp01 Can you please open a new issue, as this is indeed a regression.
